/**
 * 図の段 (phase) の題の対訳 (#2469)。
 *
 * 段の題は図のデータ (`diagram.phases[].title`) が持ち、日本語の 1 本しか無い。
 * 英語で開いた時、図の外に出す札 (`PhaseChrome`) にその日本語がそのまま出ていた。
 *
 * ## 引けない時は日本語へ落とさない
 *
 * `catalog-item-en.ts` の説明文と同じ扱い。 落とすと、英語の画面に日本語が出たことが
 * 表の抜けなのか訳し忘れなのか読めない。 引けない時は **題を出さない**
 * (札は「Phase 2 / 5」 だけになる)。 抜けは検査が実物の見本を走査して落とす。
 *
 * ## 日本語を含まない題は素通しする
 *
 * `2. ALB` や `solid / accent` のように英数字だけの題がある。
 * これらは訳す対象ではないので、表に載せずそのまま出す。
 *
 * ## 図の中の字は対象外
 *
 * ここが直すのは **図の外に出す札** だけ。 図の中に描かれる箱や矢印の名前は
 * 図そのものの訳で、別の話になる。
 *
 * ## 表の母集団
 *
 * 静的に読み込む見本 (`CATALOG_ITEMS`) と、その中の変種 (`patterns`)、
 * それに遅れて読み込む `parts` 分類 (`loadPartsItems()`) の段の題。
 * 抜けは `catalog-phase-en.test.ts` が実物を走査して落とす。
 *
 * **`parts` も入れる**。 起票時は数え方が別だとして外していたが、外すと
 * その分類の段だけ英語で題が消える (引けない時に日本語へ落とさない設計のため)。
 * 日本語が出るより悪いので、同じ表で覆う。
 */

/** 段の題が日本語を含むか。 判定は `onload-locale.spec.ts` の歯止めと同じ字の範囲で見る */
export const 日本語を含む = (字: string): boolean =>
  /[\p{Script_Extensions=Hiragana}\p{Script_Extensions=Katakana}\p{Script_Extensions=Han}]/u.test(
    字,
  );

/**
 * 段の題の対訳。 鍵は日本語の題そのもの。
 *
 * 同じ題が複数の見本に出る時は 1 件にまとめる = 文脈で訳し分けが要る題が出たら、
 * その時に題そのものを分ける (対訳表を文脈で分岐させると、どの見本がどちらを引くかが
 * 表からは読めなくなる)。
 */
export const PHASE_TITLE_EN: Record<string, string> = {
  // --- ethereum ---
  "① やりたいことを書いて出す": "1. Write what you want and send it",
  "① 取引が溜まっていく": "1. Transactions pile up",
  "① 目標ちょうどのとき": "1. When demand sits right on target",
  "① 送金を申し込む": "1. Ask to send funds",
  "② まとめ役が拾い集める": "2. A bundler picks them up",
  "② 提案者が選ばれる": "2. A proposer is chosen",
  "② 残高が足りるか確かめる": "2. Check the balance covers it",
  "② 混んできたとき": "2. When it gets busy",
  "③ ブロックに詰める": "3. Pack them into a block",
  "③ 基礎分は誰の手にも渡らない": "3. The base part goes to no one",
  "③ 数字を付け替える": "3. Move the numbers across",
  "③ 財布が自分で正しさを判断する": "3. The wallet judges validity itself",
  "④ 他の検証者が確かめる": "4. Other validators check it",
  "④ 手数料を肩代わりしてもらう": "4. Have someone else cover the fee",
  "④ 空いてきたとき": "4. When it quiets down",
  "④ 記録を残す": "4. Leave a record",
  "⑤ 確定する": "5. It becomes final",

  // --- charts ---
  "4 つを入れた後": "After the four changes",
  "5 つの気持ち": "Five states of mind",
  "今年": "This year",
  "今月": "This month",
  "今期の内訳": "This period, by part",
  "今期の見込み": "Forecast for this period",
  "今週": "This week",
  "先週": "Last week",
  "前期との比較": "Against last period",
  "前期と今期": "Last period and this one",
  "夕方": "Evening",
  "帯を引く": "Draw the bars",
  "手を付ける前": "Before any change",
  "改善後": "After the change",
  "昨年": "Last year",
  "朝": "Morning",
  "期の初め": "Start of the period",
  "来月の見込み": "Forecast for next month",
  "枝を広げる": "Spread the branches",
  "構成と役割を辿る": "Follow the parts and their roles",
  "構成を辿る": "Follow the parts",
  "段取りを引く": "Lay out the steps",
  "窓口を 1 つにした後": "After merging the entry points into one",
  "見直し後": "After the rethink",
  "見込みを足す": "Add the forecast",

  // --- styles ---
  "6 色を並べる": "Six colours side by side",
  "どの線も同じ色で引く": "Every line in the same colour",
  "上の辺から出す": "Leave from the top edge",
  "下の辺から出す": "Leave from the bottom edge",
  "先端に多重度を置く": "Multiplicity at the head",
  "先端に矢じりを置く": "Arrowhead at the head",
  "先端を塗る形と中空の形": "Filled head and hollow head",
  "出る辺を推し量る": "Let the edge be inferred",
  "動いている状態": "Running",
  "受付の上に確認を置く": "Check above reception",
  "受付の下に確認を置く": "Check below reception",
  "受付の右に確認を置く": "Check to the right of reception",
  "受付の左に確認を置く": "Check to the left of reception",
  "右の辺から出す": "Leave from the right edge",
  "同じ値で 4 つの向き": "One value, four directions",
  "左の辺から出す": "Leave from the left edge",
  "根元に多重度を置く": "Multiplicity at the tail",
  "根元に矢じりを置く": "Arrowhead at the tail",
  "根元を塗る形と中空の形": "Filled tail and hollow tail",
  "止まっている状態": "Stopped",
  "縦列を書いて矢印を飾る": "Name the lane, then style the arrow",
  "縦列を書かずに矢印を飾る": "Style the arrow without naming the lane",
  "通り道だけを強調の色で引く": "Only the path in the accent colour",
  "間隔を書かずに受付の右へ置く": "To the right of reception, with no gap given",
  "題を書いても色は残る": "The colour stays when a title is added",

  // --- patterns ---
  "不合格": "Rejected",
  "不成立の経路": "The route that does not hold",
  "中継まで": "As far as the relay",
  "仮の書き込み": "A provisional write",
  "出来事を出す": "Emit the event",
  "判定": "Decide",
  "刻む": "Tick",
  "受け手まで": "As far as the receiver",
  "受け皿まで": "As far as the handler",
  "合格": "Accepted",
  "周回 1": "Pass 1",
  "周回 2": "Pass 2",
  "周回 3": "Pass 3",
  "呼ぶ": "Call",
  "差し込みの呼び戻し": "The hook calls back",
  "成立の経路": "The route that holds",
  "書く": "Write",
  "検証": "Validate",
  "直結": "Straight through",
  "読む": "Read",
  "貫通": "Pass through",
  "起動": "Start",
  "送り手": "Sender",
  "送る": "Send",
  "配る": "Fan out",
  "開始": "Begin",
  "関数": "Function",
  "集める": "Gather",

  // --- animation ---
  "保存完遂": "Saved",
  "処理中": "Working",
  "初動 (0 → 10)": "First move (0 → 10)",
  "加工中": "Processing",
  "加速 (10 → 50)": "Speeding up (10 → 50)",
  "受注中": "Order taken",
  "変換中": "Converting",
  "夜スケールダウン (20:00)": "Scaling down at night (20:00)",
  "完了": "Done",
  "完了 (50 → 100)": "Done (50 → 100)",
  "完了 (状態 + 進捗を仕上げ)": "Done (state and progress finish together)",
  "実行中 → 完了": "Running → Done",
  "平常": "Normal",
  "待機 → 実行中": "Waiting → Running",
  "排除中": "Dropping",
  "数え上げを滑らかに進める (0 → 100)": "Count up smoothly (0 → 100)",
  "昼安定 (12:00)": "Steady at midday (12:00)",
  "朝ピーク (7:00)": "Morning peak (7:00)",
  "検証中": "Checking",
  "極混雑": "Very busy",
  "決済中": "Taking payment",
  "深夜アイドル (2:00)": "Idle overnight (2:00)",
  "混雑": "Busy",
  "準備中": "Getting ready",
  "発送中": "Shipping",
  "空のブロック": "An empty block",
  "第 1 戦 (拮抗)": "Round 1 (neck and neck)",
  "第 2 戦 (山田様が先行)": "Round 2 (Yamada ahead)",
  "第 3 戦 (佐藤様 追い上げ)": "Round 3 (Sato closing in)",
  "第 4 戦 (佐藤様 優勝)": "Round 4 (Sato wins)",
  "読込開始 (状態 + 進捗を併走)": "Loading starts (state and progress run together)",
  "配達中": "Out for delivery",

  // --- cookbook ---
  "1 回目": "1st try",
  "2 回目": "2nd try",
  "3 回目": "3rd try",
  "DB から引く": "Read from the database",
  "まとめ": "Summary",
  "保管": "Store",
  "全員へ送る": "Send to everyone",
  "処理": "Work",
  "出来事 1": "Event 1",
  "出来事 2": "Event 2",
  "出来事 3": "Event 3",
  "利用": "Use",
  "受け取った": "Received",
  "受理": "Accepted",
  "同意の確認": "Ask for consent",
  "埋める": "Fill it",
  "実行": "Run",
  "届ける": "Deliver",
  "引き換え": "Exchange",
  "待つ": "Wait",
  "押す": "Press",
  "探す": "Look it up",
  "接続の確立": "Open the connection",
  "操作": "Action",
  "書き換える": "Rewrite",
  "書き込み": "Write",
  "最初の 20 件": "First 20",
  "次の 20 件": "Next 20",
  "流す": "Stream it out",
  "点数付け": "Score",
  "無い": "Not there",
  "照会": "Query",
  "照合": "Match",
  "発行": "Issue",
  "知らせる": "Announce",
  "確かめる": "Check",
  "積む": "Queue it",
  "結果": "Result",
  "要求": "Request",
  "記す": "Note it",
  "記録": "Record",
  "許可": "Allowed",
  "超過": "Over the limit",
  "転送": "Forward",
  "返す": "Return",
  "送り込み": "Send it in",
  "送信": "Send",
  "鍵で呼ぶ": "Call with the key",
  "開く": "Open",

  // --- text-dsl ---
  "1 つから多数": "One to many",
  "1 つ以上": "One or more",
  "1. 実体の表": "1. Entity tables",
  "2. 中継表": "2. Join tables",
  "3. 多対多の 2 組": "3. Two many-to-many pairs",
  "4. 案件とタグ": "4. Projects and tags",
  "7 つの表": "Seven tables",
  "Q1 進行": "Q1 under way",
  "Q2 開始": "Q2 begins",
  "ちょうど 1 つずつ": "Exactly one each",
  "つながり": "Relationships",
  "シェア更新": "Share updated",
  "中を開く": "Open the inside",
  "中心": "Centre",
  "今の内訳を見る": "Look at the current split",
  "使う": "Uses",
  "入ってくる": "Coming in",
  "全体": "The whole",
  "全体の見取り図": "The overall map",
  "出来事": "Event",
  "動かす単位の間": "Between running units",
  "取得": "Fetch",
  "受け付けて記録する": "Take it and record it",
  "受け付ける": "Take it",
  "呼び出し": "Call",
  "問い合わせ": "Enquiry",
  "外を指す列が山形になる": "Columns pointing outward get a chevron",
  "多数から 1 つ": "Many to one",
  "多数どうし": "Many to many",
  "子まで": "Down to the child",
  "広がる": "Spreads out",
  "成功": "Succeeded",
  "持つ": "Has",
  "振り分け": "Split",
  "捌き始める": "Starts clearing",
  "案が出る": "Ideas appear",
  "無いか 1 つ": "Zero or one",
  "片方": "One side only",
  "発送する": "Ship it",
  "終わる": "Finished",
  "親": "Parent",
  "親と子": "Parent and child",
  "追いつく": "Catches up",
  "通販が伸びる": "Online sales grow",
  "進みを上げる": "Progress rises",
  "部品まで開く": "Open down to the parts",
  "鍵に下線が付く": "Keys get an underline",

  // --- presets ---
  "1 年の計画": "The year's plan",
  "1 年の計画と実績が落ち込んでから追い越す折れ線": "A line chart where the year's plan and actuals dip, then the actuals pull ahead",
  "1. users 表": "1. The users table",
  "1. クライアントの利用者": "1. The person using the client",
  "1. ブラウザ": "1. Browser",
  "1. 下書き": "1. Draft",
  "1. 下書きで書き始める": "1. Start writing as a draft",
  "1. 利用者": "1. The person using it",
  "1. 利用者が注文する": "1. A person places an order",
  "1. 利用者は 2 通りで来る": "1. People arrive by two routes",
  "1. 外の回線を 2 本引く": "1. Two lines in from outside",
  "1. 外部との境界": "1. The boundary with the outside",
  "1. 待機": "1. Waiting",
  "1. 抽象クラスとインターフェース": "1. Abstract classes and interfaces",
  "1. 注文が受付に渡る": "1. The order reaches reception",
  "1. 注文を出す": "1. Place the order",
  "1. 申請を出す": "1. Submit the claim",
  "1. 近い拠点へ繋ぐ": "1. Connect to the nearest site",
  "1. 領収書を添えて申請する": "1. Claim with the receipt attached",
  "2 つの軸で 4 象限に分けて優先度を決める図": "A chart that splits two axes into four quadrants to set priorities",
  "2. サービスの処理": "2. The service does the work",
  "2. スイッチ A": "2. Switch A",
  "2. 入口で受ける": "2. Taken at the entrance",
  "2. 処理中の中の読み込み": "2. Loading, inside Running",
  "2. 出して受付済へ": "2. Submit it and move to Accepted",
  "2. 出して査読を待つ": "2. Submit it and wait for review",
  "2. 合言葉を確かめる": "2. Check the password",
  "2. 在庫を押さえる": "2. Hold the stock",
  "2. 境の壁で受ける": "2. Taken at the boundary wall",
  "2. 審査": "2. Review",
  "2. 振込とカードの継承": "2. Transfer and card inherit",
  "2. 数を確かめる": "2. Check the count",
  "2. 明細に商品が並ぶ": "2. Items line up on the order lines",
  "2. 注文する": "2. Place an order",
  "2. 画面の部品は S3 から": "2. Page assets come from S3",
  "2. 継承": "2. Inheritance",
  "2. 金額で道を分ける": "2. The amount splits the route",
  "3. ECS のタスク": "3. The ECS task",
  "3. はいなら承認": "3. Yes means approved",
  "3. アプリのサーバー": "3. The application server",
  "3. 受付済のまま催促する": "3. Chase it while still Accepted",
  "3. 在庫を押さえる": "3. Hold the stock",
  "3. 在庫を持つ": "3. Holds stock",
  "3. 壁どうしで生死を見る": "3. The walls watch each other for life",
  "3. 実装": "3. Implementation",
  "3. 押さえた": "3. Held",
  "3. 振り分けの前にログインを確かめる": "3. Check the sign-in before routing",
  "3. 数を押さえる": "3. Hold the count",
  "3. 明細を持つ": "3. Has order lines",
  "3. 無い分を振り分けへ回す": "3. Send what is missing on to routing",
  "3. 直して出し直す": "3. Fix it and submit again",
  "3. 認証サービス": "3. The sign-in service",
  "3. 財布の継承と実装": "3. The wallet inherits and implements",
  "3. 高い申請は上長に回す": "3. Large claims go to the manager",
  "4. 4 度目は見送りで終わる": "4. The fourth time it ends in a pass",
  "4. アプリ": "4. The application",
  "4. ゲートウェイの実装": "4. The gateway implements it",
  "4. 中心の交換機へ渡す": "4. Hand it to the central switch",
  "4. 動かす場所へ渡す": "4. Hand it to where it runs",
  "4. 商品を分類する": "4. Put items into categories",
  "4. 引き落とす": "4. Take the payment",
  "4. 控えを書く": "4. Write the copy",
  "4. 支払いが弾かれる": "4. The payment is refused",
  "4. 支払って終わる": "4. Pay and finish",
  "4. 注文 API へ転送する": "4. Forward to the order API",
  "4. 自分への関係": "4. A relationship to itself",
  "4. 認めなければ却下で終える": "4. If it is not approved, end in rejection",
  "4. 集約": "4. Aggregation",
  "5. 2 つの道が照合で合流する": "5. The two routes meet at the match",
  "5. コンポジション": "5. Composition",
  "5. 交換機 2 台を束ねる": "5. Bond the two switches",
  "5. 分類の親子": "5. Parent and child categories",
  "5. 取り消して終わる": "5. Cancel and finish",
  "5. 取引のコンポジション": "5. The transaction is composed of parts",
  "5. 在庫数を一時保存から読む": "5. Read the stock count from the cache",
  "5. 後でやる分を積む": "5. Queue what is left for later",
  "5. 押さえを延ばす": "5. Extend the hold",
  "5. 控えを作る": "5. Make a copy",
  "5. 発送を頼む": "5. Ask for shipping",
  "5. 認められて予約に入る": "5. Approved, and it moves to Scheduled",
  "6. 1 件ずつ取り出す": "6. Take them out one at a time",
  "6. サーバーを 2 台ぶら下げる": "6. Hang two servers off it",
  "6. 公開の前に取りやめる": "6. Call it off before it goes live",
  "6. 出荷を頼む": "6. Ask for dispatch",
  "6. 別の払い方を聞く": "6. Ask for another way to pay",
  "6. 受け付けた": "6. Accepted",
  "6. 台帳に書いて写しを作る": "6. Write to the ledger and make a copy",
  "6. 役割を割り当てる": "6. Assign roles",
  "6. 関連と依存": "6. Association and dependency",
  "6. 領収書と仕訳": "6. Receipts and journal entries",
  "6. 領収書と金額が合うかを判断する": "6. Judge whether the receipt matches the amount",
  "7. 2 つの道が合流する": "7. The two routes meet",
  "7. もう一度引き落とす": "7. Take the payment again",
  "7. サーバーどうしが読み書きする": "7. The servers read and write to each other",
  "7. 仕訳の参照とリスク判定": "7. Journal lookups and risk judgement",
  "7. 住所を登録する": "7. Register an address",
  "7. 合わなければ差し戻す": "7. If they do not match, send it back",
  "7. 時刻が来て公開する": "7. The time arrives and it goes live",
  "7. 知らせを待ち行列に置く": "7. Put the notice on the queue",
  "7. 覚え書きを先に見る": "7. Look at the cache first",
  "8. 受け付けて返す": "8. Accept it and reply",
  "8. 台帳へ読み書きする": "8. Read and write to the ledger",
  "8. 手入れの道を分ける": "8. Keep a separate route for maintenance",
  "8. 支払と配送": "8. Payment and delivery",
  "8. 発送係が引き取る": "8. The dispatch worker picks it up",
  "8. 結果が利用者へ返る": "8. The result comes back to the person",
  "8. 誤りが見つかって取り下げる": "8. A mistake is found and it is withdrawn",
  "8. 通知への依存": "8. A dependency on notifications",
  "9. 住所を指す 2 本": "9. Two links pointing at the address",
  "クラウド・ネットワーク構成を階層で示す図": "A chart showing cloud and network layout in layers",
  "システムの構成要素と接続を配置で示す図": "A chart showing a system's parts and links by where they sit",
  "タスクの期間と依存関係を横棒で示す進捗図": "A progress chart showing task lengths and dependencies as horizontal bars",
  "ネットワーク機器とセグメントの接続関係を示す図": "A chart showing how network devices and segments connect",
  "ユーザー体験の感情変化をステップ順に示す図": "A chart showing how a person feels at each step of the experience",
  "中心の主題から発想を放射状に広げる図": "A chart spreading ideas outward from a subject at the centre",
  "二度目の使い方を直す": "Fix how it works the second time",
  "仕分けた直後": "Right after sorting",
  "作る部門が部になる": "The build team becomes a division",
  "価値の見積りを直す": "Revise the value estimates",
  "先に作る所を決める": "Decide what to build first",
  "先月": "Last month",
  "全体に対する内訳の割合を示す円グラフ": "A pie chart showing each part's share of the whole",
  "処理の順番を左から右へ 1 本の流れで示す図": "A chart showing the order of work as one line from left to right",
  "処理を役割ごとに縦列に分けて流れを示す図": "A chart splitting the work into lanes by role to show the flow",
  "分岐や判定を含む処理の流れを示す図": "A chart showing a flow that branches and decides",
  "半年前の内訳": "The split six months ago",
  "各段階での離脱率を示す絞込みの図": "A funnel showing how many drop away at each stage",
  "品質を独立させる": "Make quality its own team",
  "問い合わせの種類ごとの割合が半年で入れ替わる円グラフ": "A pie chart where the mix of enquiry types swaps around over six months",
  "土台が1月延びる": "The groundwork slips by a month",
  "土台の 1 月の遅れが後ろの作業へ次々と波及する進捗図": "A progress chart where a one-month slip in the groundwork ripples through everything after it",
  "夏に落ち込む": "It dips in summer",
  "当初の計画": "The original plan",
  "後にする所を決める": "Decide what to leave for later",
  "手間と価値の見積りを分けて直し、枠の中身だけが入れ替わる四象限図": "A four-quadrant chart where effort and value are revised separately and only the contents of the boxes move",
  "手間の見積りを直す": "Revise the effort estimates",
  "抜けが最も大きい一か所を直すと後ろが順に増える漏斗": "A funnel where fixing the single biggest leak lifts everything after it",
  "探しやすさを直す": "Make things easier to find",
  "支払いの選び方を直す": "Fix how payment is chosen",
  "改善前": "Before the change",
  "春は計画どおり": "Spring goes to plan",
  "昨年の内訳": "Last year's split",
  "時系列のやり取りを縦の時間軸で並べる図": "A chart laying out an exchange over time down a vertical axis",
  "時系列データの推移を線で示す折れ線グラフ": "A line chart showing how values move over time",
  "書き出した時": "When it was written out",
  "書き出した観点を先と後に仕分けて中心の方針が決まる枝分かれ図": "A branching chart where the points written out are sorted into now and later, settling the direction at the centre",
  "注文の変更が使い方の質問へ移る": "Order changes give way to questions about use",
  "注文を受けてから発送の知らせを送るまでのクラウド構成図": "A cloud layout from taking an order to sending the dispatch notice",
  "画面を作るも延びる": "Building the screens slips too",
  "直す前": "Before the fix",
  "秋に戻す": "Autumn brings it back",
  "立ち上げから育つにつれて課が部になり人数が増える組織図": "An org chart where, as it grows from launch, sections become divisions and headcount rises",
  "立ち上げた時": "At launch",
  "組織を作った時": "When the organisation was formed",
  "経費の申請を金額と領収書で分けて振込まで追うフローチャート": "A flowchart following an expense claim by amount and receipt through to payment",
  "見直し前": "Before the rethink",
  "親子関係を縦階層で示す組織図・木構造": "An org chart or tree showing parent and child down the levels",
  "計画": "Plan",
  "詰まりが後ろへ移る": "The bottleneck moves further back",
  "買い物の道筋にある 2 つの落ち込みを順に直す図": "A chart fixing, one after the other, the two dips along the shopping journey",
  "配送の問い合わせが在庫の確認へ移る": "Delivery enquiries give way to stock checks",
  "階層状態や遷移の処理を持つ入れ子の状態遷移図": "A nested state chart with layered states and work on the transitions",

  // --- primitives ---
  "actor の数が動く": "The actor count moves",
  "admin が動く": "admin moves",
  "api が動く": "api moves",
  "backend が動く": "backend moves",
  "cache が動く": "cache moves",
  "card の数が動く": "The card count moves",
  "cdn が動く": "cdn moves",
  "cloud が動く": "cloud moves",
  "database が動く": "database moves",
  "decision が動く": "decision moves",
  "developer が動く": "developer moves",
  "event の数が動く": "The event count moves",
  "external-user が動く": "external-user moves",
  "frontend が動く": "frontend moves",
  "function の数が動く": "The function count moves",
  "merkle-tree が動く": "merkle-tree moves",
  "message-bus が動く": "message-bus moves",
  "microservice が動く": "microservice moves",
  "oracle が動く": "oracle moves",
  "person が動く": "person moves",
  "queue が動く": "queue moves",
  "service が動く": "service moves",
  "shape-api-gateway の数が動く": "The shape-api-gateway count moves",
  "shape-atm の数が動く": "The shape-atm count moves",
  "shape-auditor の数が動く": "The shape-auditor count moves",
  "shape-bank の数が動く": "The shape-bank count moves",
  "shape-bitcoin-chain の数が動く": "The shape-bitcoin-chain count moves",
  "shape-blockchain の数が動く": "The shape-blockchain count moves",
  "shape-blockchain-node の数が動く": "The shape-blockchain-node count moves",
  "shape-brokerage の数が動く": "The shape-brokerage count moves",
  "shape-cdn-edge の数が動く": "The shape-cdn-edge count moves",
  "shape-cloud の数が動く": "The shape-cloud count moves",
  "shape-credit-card の数が動く": "The shape-credit-card count moves",
  "shape-customer-service の数が動く": "The shape-customer-service count moves",
  "shape-cylinder の数が動く": "The shape-cylinder count moves",
  "shape-diamond の数が動く": "The shape-diamond count moves",
  "shape-ethereum-chain の数が動く": "The shape-ethereum-chain count moves",
  "shape-exchange の数が動く": "The shape-exchange count moves",
  "shape-file の数が動く": "The shape-file count moves",
  "shape-folder の数が動く": "The shape-folder count moves",
  "shape-gear の数が動く": "The shape-gear count moves",
  "shape-hexagon の数が動く": "The shape-hexagon count moves",
  "shape-iot-sensor の数が動く": "The shape-iot-sensor count moves",
  "shape-lawyer の数が動く": "The shape-lawyer count moves",
  "shape-message-bubble の数が動く": "The shape-message-bubble count moves",
  "shape-mobile-device の数が動く": "The shape-mobile-device count moves",
  "shape-network-node の数が動く": "The shape-network-node count moves",
  "shape-nft の数が動く": "The shape-nft count moves",
  "shape-notary の数が動く": "The shape-notary count moves",
  "shape-online-shop の数が動く": "The shape-online-shop count moves",
  "shape-payment-provider の数が動く": "The shape-payment-provider count moves",
  "shape-person の数が動く": "The shape-person count moves",
  "shape-regulator の数が動く": "The shape-regulator count moves",
  "shape-robot-arm の数が動く": "The shape-robot-arm count moves",
  "shape-rpc-node の数が動く": "The shape-rpc-node count moves",
  "shape-satellite の数が動く": "The shape-satellite count moves",
  "shape-server-rack の数が動く": "The shape-server-rack count moves",
  "shape-smart-contract の数が動く": "The shape-smart-contract count moves",
  "shape-stack の数が動く": "The shape-stack count moves",
  "shape-storefront の数が動く": "The shape-storefront count moves",
  "shape-token の数が動く": "The shape-token count moves",
  "shape-trader の数が動く": "The shape-trader count moves",
  "shape-trust-bank の数が動く": "The shape-trust-bank count moves",
  "shape-wallet の数が動く": "The shape-wallet count moves",
  "shape-warehouse の数が動く": "The shape-warehouse count moves",
  "shape-website の数が動く": "The shape-website count moves",
  "shape-window の数が動く": "The shape-window count moves",
  "signer が動く": "signer moves",
  "storage の数が動く": "The storage count moves",
  "user-group が動く": "user-group moves",
  "webhook が動く": "webhook moves",
  "1. @花子": "1. @hanako",
  "1. Android のアプリ": "1. The Android app",
  "1. iOS のアプリ": "1. The iOS app",
  "1. サポート担当": "1. Support agent",
  "1. ファナックの腕": "1. The FANUC arm",
  "1. 代理人": "1. The agent",
  "1. 会社案内": "1. The company site",
  "1. 作者": "1. The creator",
  "1. 供給者": "1. The supplier",
  "1. 個人投資家": "1. A private investor",
  "1. 山田商店の通販": "1. Yamada Store's online shop",
  "1. 検証役": "1. The validator",
  "1. 注文画面/": "1. The order screen /",
  "1. 温度計": "1. The thermometer",
  "1. 発行者": "1. The issuer",
  "1. 監査法人": "1. The audit firm",
  "1. 社員の携帯": "1. An employee's phone",
  "1. 課題 #42": "1. Issue #42",
  "1. 買い手": "1. The buyer",
  "1. 資産運用者": "1. The asset manager",
  "1. 購入者": "1. The purchaser",
  "1. 送金者": "1. The sender",
  "1. 金融庁": "1. The financial regulator",
  "1.5 倍で描く": "Draw at 1.5x",
  "2. BTC の本番網": "2. The live Bitcoin network",
  "2. GitHub の実行環境": "2. GitHub's runner",
  "2. みずほ銀行": "2. Mizuho Bank",
  "2. 三井住友信託": "2. Sumitomo Mitsui Trust",
  "2. 不具合 #1234": "2. Bug #1234",
  "2. 会計帳簿": "2. The accounting ledger",
  "2. 公証役場": "2. The notary office",
  "2. 分散型取引所": "2. The decentralised exchange",
  "2. 取引の明細": "2. The transaction detail",
  "2. 基幹の中継器": "2. The core relay",
  "2. 外観の検査": "2. The visual inspection",
  "2. 楽天市場": "2. Rakuten Ichiba",
  "2. 橋渡し": "2. The bridge",
  "2. 監査報告書": "2. The audit report",
  "2. 通知の配達": "2. Delivering the notification",
  "2. 配備の流れ": "2. The deployment flow",
  "2. 野村証券": "2. Nomura Securities",
  "2. 高さ 8123456": "2. Height 8123456",
  "Bitcoin の送金": "Sending bitcoin",
  "NFT の売買": "Buying and selling an NFT",
  "NFT の発行": "Minting an NFT",
  "サイトの配信": "Serving a site",
  "フローの矢印を書いた端のとおりに繋ぐ": "Connect the flow exactly at the edges the arrow names",
  "並びで決まる札": "Markers decided by order",
  "作業の流れ": "A work flow",
  "信託資産": "Trust assets",
  "分散型の貸し出し": "Decentralised lending",
  "受付の窓口の縦列を右へ 120、下へ 40 ずらす": "Shift the reception lane 120 right and 40 down",
  "合意の形成": "Reaching consensus",
  "名札の余白を 40 にする": "Set the box padding to 40",
  "問い合わせの流れ": "An enquiry flow",
  "始まりと終わりの札": "Start and end markers",
  "工場の組立": "Assembly on a factory line",
  "広さを横 1400 と縦 800 にする": "Set the size to 1400 wide and 800 tall",
  "拠点での処理": "Work done at the edge site",
  "携帯アプリの API": "A mobile app's API",
  "暗号資産の送金": "Sending crypto",
  "書かない時の並び": "The order when nothing is given",
  "横に並べる": "Lay them out across",
  "段を分けて書いた札": "Markers written on separate phases",
  "決済の流れ": "A settlement flow",
  "法務の流れ": "A legal flow",
  "注文するの箱を右へ 40、下へ 60 ずらす": "Shift the Order box 40 right and 60 down",
  "注文の名前を右へ 40、上へ 24 ずらす": "Shift the order's name 40 right and 24 up",
  "版の配備": "Deploying a version",
  "監査の報告": "Reporting an audit",
  "監査の流れ": "An audit flow",
  "社内の網で 2 本の縦列を囲む": "Wrap two lanes in the internal network",
  "社外と社内の網を別の枠で囲む": "Wrap the outside and inside networks in separate frames",
  "箱の位置だけで縦列を読む": "Read the lanes from box position alone",
  "箱の間を 80 にする": "Set the gap between boxes to 80",
  "縦に積む": "Stack them down",
  "縦の点線で縦列を追う": "Follow the lanes with a dotted vertical line",
  "縦列の幅を 520 に揃える": "Make every lane 520 wide",
  "縦列の間を 400 にする": "Set the gap between lanes to 400",
  "縦列を 1 本ずつ並べる": "Lay the lanes out one by one",
  "自動で決まった位置に置く": "Leave them where the layout puts them",
  "衛星から台帳へ": "From satellite to ledger",
  "規制への対応": "Meeting the regulations",
  "計測値を台帳へ": "Readings onto the ledger",
  "証券取引": "Trading securities",
  "通信の経路": "A network path",
  "通知": "A notification",
  "通貨の橋渡し": "Bridging a token",
  "通貨の発行": "Issuing a token",
  "通販の支払い": "Paying at an online shop",
  "通販の注文": "Ordering from an online shop",
  "銀行の送金": "A bank transfer",
  "開発と運用": "Development and operations",
  "間隔をまとめて 120 にする": "Set every gap to 120 at once",
  "間隔を書かない": "Give no spacing at all",

  // --- interactive ---
  "0 度を見る": "Look at 0 degrees",
  "0% を見る": "Look at 0%",
  "1 つが停止": "One has stopped",
  "1 つに寄る": "It leans to one",
  "1 ブロック目": "Block 1",
  "1 件だけ": "Just one",
  "1 件目": "The first one",
  "1 日ぶん": "One day's worth",
  "1 本だけ出す": "Show one line only",
  "1 案に集まる": "They gather on one idea",
  "1 段目で分かれる": "It splits at the first level",
  "1 点だけ入れる": "Put in a single point",
  "1 箱で見る": "See it in one box",
  "1 経路": "One route",
  "1 行目を見る": "Look at row 1",
  "1.2 倍で見る": "See it at 1.2x",
  "1.5 倍で見る": "See it at 1.5x",
  "180 度まで並べる": "Lay them out to 180 degrees",
  "2 つ目まで伝わる": "It reaches the second",
  "2 ブロック目": "Block 2",
  "2 倍を出す": "Show double",
  "2 回押す": "Press twice",
  "2 本に増える": "It grows to two lines",
  "2 本伸ばす": "Extend two lines",
  "2 段階認証": "Two-step sign-in",
  "2 箱で見る": "See it in two boxes",
  "2 行目を見る": "Look at row 2",
  "25% を見る": "Look at 25%",
  "3 つ入れる": "Put in three",
  "3 ブロック目": "Block 3",
  "3 個": "Three",
  "3 日前の予報": "The forecast three days out",
  "3 本が揃う": "Three lines line up",
  "3 箱が同時に追う": "Three boxes follow at once",
  "3 行目を見る": "Look at row 3",
  "3 角を見る": "Look at three corners",
  "33% と並べる": "Line it up with 33%",
  "4 つ目まで伝わる": "It reaches the fourth",
  "4 区画を見る": "Look at the four quadrants",
  "4 指標が揃う": "Four measures line up",
  "4 本に広げる": "Spread it to four lines",
  "50% と並べる": "Line it up with 50%",
  "6 つ揃う": "Six line up",
  "6 角と並べる": "Line it up with six corners",
  "66% まで並べる": "Lay them out to 66%",
  "75% まで並べる": "Lay them out to 75%",
  "8 角まで並べる": "Lay them out to eight corners",
  "90 度と並べる": "Line it up with 90 degrees",
  "A だけ": "A only",
  "B を並べる": "Put B alongside",
  "いまの回転数": "The current revolutions",
  "いまの室温": "The current room temperature",
  "いまの成績": "The current standings",
  "いまの残量": "How much is left now",
  "いまの状態": "The current state",
  "いまの確信度": "How sure it is now",
  "いまの評価": "The current rating",
  "いまの課題": "The current task",
  "いまの通知": "The current notification",
  "さらに下へ": "Further down",
  "ずれを見る": "Look at the gap",
  "つまみで動かす": "Move it with the slider",
  "つまみを持つ": "Take hold of the slider",
  "ばらつく": "They scatter",
  "ほぼ並ぶ": "They almost line up",
  "やり取りが続く": "The exchange carries on",
  "キューイング": "Queued",
  "コードを受け取る": "Receive the code",
  "セッション発行": "Session issued",
  "ドロップ受信": "Drop received",
  "プレビュー表示": "Preview shown",
  "リトライ": "Retry",
  "一次検証": "First check",
  "一部が劣化": "Part of it degrades",
  "上がる": "It rises",
  "上の 2 段階": "The top two levels",
  "上限ちょうど": "Right on the limit",
  "上限を超える": "Over the limit",
  "下がった月": "The month it fell",
  "下の 3 段階": "The bottom three levels",
  "下へ移る": "Move down",
  "下へ進む": "Go further down",
  "並の帯を見る": "Look at the middle band",
  "中の札": "The middle marker",
  "中ほどへ降りる": "Come down to the middle",
  "中ほどまで": "As far as the middle",
  "中心を置く": "Place the centre",
  "中間のプラン": "The middle plan",
  "予選の点": "Heats score",
  "今期を見る": "Look at this period",
  "伸びる": "It grows",
  "低い優先度まで": "Down to low priority",
  "低い帯": "The low band",
  "低の札": "The low marker",
  "作業が進む": "The work moves on",
  "依頼した直後": "Just after the request",
  "信号を見る": "Look at the signal",
  "値が渡る": "The value passes across",
  "偏った形": "A lopsided shape",
  "偏りが出る": "A lean appears",
  "債券を増やす": "Add more bonds",
  "元の値を置く": "Place the original value",
  "元の値を見る": "Look at the original value",
  "先頭を読む": "Read the head",
  "入力の途中": "Part way through typing",
  "入口だけ": "The entrance only",
  "入口に立つ": "Standing at the entrance",
  "全て稼働": "All running",
  "全体が揃う": "The whole thing lines up",
  "公開する": "Publish it",
  "再生中": "Playing",
  "再生位置": "Playback position",
  "再生完了": "Playback finished",
  "再生済": "Played",
  "再生状態": "Playback state",
  "分け直す": "Split it again",
  "分散する": "They spread out",
  "切り替える": "Switch it",
  "初回到達": "First arrival",
  "初期の並び": "The starting order",
  "別の記事": "A different article",
  "利用者を見る": "Look at the person using it",
  "削除を並べる": "Put deletions alongside",
  "前日の予報": "Yesterday's forecast",
  "前期を見る": "Look at last period",
  "割引率": "Discount rate",
  "創業した頃": "Around the founding",
  "動かす側を見る": "Look at the side that moves",
  "動き出す": "It starts moving",
  "午前の予定": "The morning's schedule",
  "午後まで": "Through the afternoon",
  "半ばまで再生": "Played to the middle",
  "半分も出す": "Show the half as well",
  "半分進む": "Half way through",
  "半年先まで": "Six months ahead",
  "南半球まで": "As far as the southern hemisphere",
  "収支が出る": "The balance comes out",
  "受け取り手を決める": "Choose the recipient",
  "受け手まで届く": "It reaches the receiver",
  "受信した直後": "Just after it arrives",
  "右の枝も分かれる": "The right branch splits too",
  "右へ移る": "Move right",
  "右上がりに整う": "It settles into a rise",
  "右上の区画": "The top-right quadrant",
  "名前を受ける": "Take the name",
  "商品購入": "Item bought",
  "四角に届く": "It reaches the square",
  "図に出入りする": "In and out of the diagram",
  "固定の側と比べる": "Compare against the fixed side",
  "土台を足す": "Add the groundwork",
  "均等に分ける": "Split it evenly",
  "基準を置く": "Place the baseline",
  "場所を移る": "It moves place",
  "増える分": "The part that grows",
  "増やす": "Add more",
  "増減と円を見る": "Look at the change and the circle",
  "夜の会": "The evening session",
  "大きく重なる": "They overlap a lot",
  "完了と失敗": "Done and failed",
  "完了の印": "The done marker",
  "実行中": "Running",
  "実行状態": "Run state",
  "寒い帯": "The cold band",
  "対角だけ": "The diagonal only",
  "少ない語": "Fewer words",
  "履歴と並べる": "Put the history alongside",
  "山が右へ移る": "The peak moves right",
  "左の枝が分かれる": "The left branch splits",
  "左上を見る": "Look at the top left",
  "左下の区画": "The bottom-left quadrant",
  "差が出る": "A gap appears",
  "差が大きい": "The gap is wide",
  "差が確定する": "The gap settles",
  "差が開く": "The gap widens",
  "差し引き": "Net",
  "差を出す": "Show the gap",
  "差を均す": "Even the gap out",
  "帯を並べる": "Put the bands alongside",
  "平常の稼働": "Running normally",
  "平常の記録": "A normal record",
  "平日だけ": "Weekdays only",
  "年内が揃う": "The year fills in",
  "広い語で引く": "Search with a broad word",
  "広まる": "It spreads",
  "序盤の値": "The early value",
  "底を打つ": "It bottoms out",
  "引き換える": "Redeem it",
  "引けの値動き": "The close",
  "弧にも届く": "It reaches the arc too",
  "弱い (段階 1)": "Weak (level 1)",
  "強い (段階 4)": "Strong (level 4)",
  "当日の予報": "Today's forecast",
  "形が整う": "The shape settles",
  "形で読む": "Read it by shape",
  "役員を置く": "Place the officers",
  "復帰する": "It comes back",
  "応答返却": "Response returned",
  "悪い帯を見る": "Look at the bad band",
  "情報と注意": "Info and warning",
  "手前だけ決まる": "Only the near side settles",
  "打ち始め": "Start typing",
  "投稿した直後": "Just after posting",
  "押し出される": "It gets pushed out",
  "押すと値が変わる": "Press and the value changes",
  "押す前": "Before pressing",
  "拠点は 1 つ": "One site only",
  "持ち直す": "It recovers",
  "振れる": "It swings",
  "接戦の状態": "Neck and neck",
  "推移で読む": "Read it from the movement",
  "改善中 (段階 1 → 3)": "Improving (level 1 → 3)",
  "数え上げを見る": "Watch the count up",
  "数でも読む": "Read it by number too",
  "数を選ぶ": "Choose the number",
  "文字でも出す": "Show the text as well",
  "文字を打つ": "Type some text",
  "新価格": "New price",
  "新着が付く": "A new one arrives",
  "既読": "Read",
  "日時を選ぶ": "Choose the date and time",
  "旧価格": "Old price",
  "昼の会": "The midday session",
  "昼の値動き": "Midday movement",
  "時計表示": "Clock display",
  "時間の元を見る": "Look at the time source",
  "時間表示": "Time display",
  "暑い帯まで": "Up to the hot band",
  "書き始め": "Start writing",
  "最も安いプラン": "The cheapest plan",
  "最も深い階層": "The deepest level",
  "最も高いプラン": "The dearest plan",
  "最上位に居る": "At the very top",
  "最初の 2 段": "The first two levels",
  "最後まで": "All the way to the end",
  "月の初め": "Start of the month",
  "月の半ば": "Middle of the month",
  "月の終わり": "End of the month",
  "朝の会": "The morning session",
  "朝の値動き": "Morning movement",
  "朝の在席": "Who is in, in the morning",
  "期の半ば": "Middle of the period",
  "期の始め": "Start of the period",
  "期の終わり": "End of the period",
  "未入力": "Nothing typed",
  "未選択": "Nothing chosen",
  "本人認証": "Identity check",
  "札でも出す": "Show it on a marker too",
  "枝分かれ": "It branches",
  "株式に寄る": "It leans to equities",
  "梱包と発送": "Packing and dispatch",
  "棒に届く": "It reaches the bar",
  "横ばい": "Flat",
  "横並び": "Side by side",
  "次に続く": "On to the next",
  "歩留まりが上がる": "The yield rises",
  "残り 1 件": "One left",
  "決勝の点": "Final score",
  "注意が出る": "A warning appears",
  "注意に上がる": "It rises to warning",
  "活発になる": "It gets busy",
  "流入元が増える": "More sources bring people in",
  "混雑する": "It gets crowded",
  "減る分が入る": "The part that falls comes in",
  "準決勝": "Semi-final",
  "点数を増やす": "Raise the score",
  "熱の升目を見る": "Look at the heat grid",
  "状態の点を見る": "Look at the state dots",
  "現在の帯": "The current band",
  "現在を見る": "Look at now",
  "現在値を見る": "Look at the current value",
  "現場が増える": "More sites appear",
  "画面から始める": "Start from the screen",
  "異常が出る": "Something goes wrong",
  "異常と成功": "Failure and success",
  "異常に上がる": "It rises to error",
  "白を並べる": "Put the white alongside",
  "目標を並べる": "Put the target alongside",
  "着手前": "Before starting",
  "矢印と縦列を押す": "Press the arrow and the lane",
  "短い記事": "A short article",
  "確定する": "It settles",
  "確認を経る": "It goes through a check",
  "票が入り始める": "Votes start coming in",
  "票が割れる": "The vote splits",
  "票が集まる": "Votes gather",
  "秒数": "Seconds",
  "積み上がる": "They stack up",
  "立ち上げ": "Start it up",
  "端まで届く": "It reaches the edge",
  "符号を入れる": "Put the sign in",
  "等倍で見る": "See it at actual size",
  "箱を動かす・落とす": "Drag the box and drop it",
  "終盤に入る": "Into the closing stretch",
  "組み立てまで揃う": "Everything down to assembly lines up",
  "経路と円に届く": "It reaches the route and the circle",
  "絞られる": "It narrows",
  "絞り切る": "Narrow it all the way",
  "絵にする": "Turn it into a picture",
  "緑を見る": "Look at the green",
  "線に出る": "It shows on the line",
  "締め切り": "Deadline",
  "良い帯と目標": "The good band and the target",
  "色を選ぶ": "Choose the colour",
  "落ち着く": "It settles down",
  "表示の上限": "The display ceiling",
  "表記も揃う": "The wording lines up too",
  "複数選ぶ": "Choose several",
  "西へ広がる": "It spreads west",
  "見本に伝わる": "It carries through to the sample",
  "解決する": "It is resolved",
  "解約率も導く": "The churn rate comes out too",
  "記帳完了": "Booked",
  "設計だけ": "Design only",
  "認可を求める": "Ask for authorisation",
  "認証要求": "Sign-in requested",
  "語が増える": "More words",
  "語を足す": "Add a word",
  "誤りが混ざる": "A mistake creeps in",
  "説明欄に出る": "It shows in the description",
  "読み取る": "Read it",
  "賛成が増える": "More agree",
  "賛成に寄る": "It leans to agreement",
  "赤を見る": "Look at the red",
  "起点を置く": "Place the starting point",
  "軽い処理": "Light work",
  "軽微な知らせ": "A minor notice",
  "追い上げる": "It closes in",
  "追加を見る": "Look at the additions",
  "追随する側": "The side that follows",
  "送った直後": "Just after sending",
  "送り手を見る": "Look at the sender",
  "送信の直前": "Just before sending",
  "通常と巡航": "Normal and cruising",
  "通常運転": "Running as usual",
  "通知のきっかけ": "What triggers the notification",
  "連なる": "They chain together",
  "連絡先まで": "Down to the contact",
  "週の初め": "Start of the week",
  "週の半ば": "Middle of the week",
  "週の始まり": "The week begins",
  "週の終わり": "End of the week",
  "週末も入る": "The weekend comes in too",
  "過回転まで": "Up to over-revving",
  "適用する": "Apply it",
  "選ぶ / キーを押す": "Choose, or press a key",
  "配信中": "Streaming",
  "配信完了": "Streaming finished",
  "配達中まで": "Through to out for delivery",
  "配達完了": "Delivered",
  "重い処理が入る": "Heavy work comes in",
  "重なりなし": "No overlap",
  "重なる": "They overlap",
  "重みの幅が広がる": "The weights spread wider",
  "銀行確定": "Settled at the bank",
  "長く押す": "Press and hold",
  "開始の形": "The starting shape",
  "静かなスレッド": "A quiet thread",
  "静かな期間": "A quiet spell",
  "順位が入れ替わる": "The order swaps",
  "頭文字を取る": "Take the initial",
  "題と抜粋が伸びる": "The title and excerpt grow",
  "高い優先度": "High priority",
  "高い帯まで": "Up to the high band",
  "高さが入れ替わる": "The heights swap",
  "高の札": "The high marker",
  "黄を見る": "Look at the yellow",
  "黒の手前を置く": "Place the near side of the black",

  // --- parts (遅れて読み込む分類、 #2469 で一緒に覆った) ---
  "水位上昇": "The level rises",
  "層拡大": "The layer grows",
  "状態が立ち上がる": "The state comes up",
  "満ちていく": "It fills up",
  "弧が伸びる": "The arc extends",
  "カウント上昇": "The count rises",
  "緑が点く": "The green lights up",
  "競争": "A race",
  "輪が回る": "The ring turns",
  "流れが通る": "The flow gets through",
  "水位変動": "The level moves",
  "推移を描く": "Draw the movement",
  "分配表示": "Show the split",
  "釣り合いを見せる": "Show the balance",
  "段取りを見せる": "Show the steps",
  "状態を見せる": "Show the state",
  "通知表示": "Show the notification",
  "指標が上がる": "The measure rises",
  "時間の並びを見せる": "Show the order in time",
  "充電中": "Charging",
  "気温上昇": "The temperature rises",
  "心拍推移": "Heart rate over time",
  "3 つ点く": "Three light up",
  "対比": "Side by side",
  "切から入へ": "From off to on",
  "加速": "Speeding up",
  "受信増加": "More arrive",
  "毎秒の件数が増える": "The rate per second rises",
  "負荷変動": "The load moves",
  "時刻更新": "The clock updates",
  "時間経過": "Time passes",
  "メッセージが届く": "A message arrives",
  "人物の絵が現れる": "The person's picture appears",
  "料金表示": "Show the price",
  "使用量増加": "Usage rises",
  "帯域変動": "The bandwidth moves",
  "日が差す": "The sun comes out",
  "3 指標推移": "Three measures over time",
  "進捗が進む": "Progress moves on",
  "音量変化": "The volume changes",
  "段取りが進む": "The steps move on",
  "予算消化": "The budget is spent",
  "週間表示": "Show the week",
  "全ての段が動く": "Every phase moves",
  "商品追加": "An item is added",
  "位置が定まる": "The position settles",
  "通知増加": "More notifications",
  "入力が伸びる": "The input grows",
  "いいね急増": "Likes jump",
  "しおりが挿さる": "A bookmark goes in",
  "収入": "Income",
  "経験値が上がる": "Experience rises",
  "実績が解放される": "An achievement unlocks",
  "割引拡大": "The discount widens",
  "再生が始まる": "Playback starts",
  "同期進行": "Syncing",
  "時刻が迫る": "The time draws near",
  "強度が上がる": "The intensity rises",
  "半径拡大": "The radius grows",
  "同期上昇": "Sync rises",
  "s1 進行": "s1 under way",
  "s2 進行": "s2 under way",
  "s3 進行": "s3 under way",
  "ひな形の差し替え": "Swap the template",
  "膨張": "It expands",
  "収縮": "It contracts",
  "満潮": "High tide",
  "引き潮": "Ebb tide",
  "全ての枡が同時に動く": "Every cell moves at once",
  "残り時間が減る": "The time left falls",
  "1 周": "One turn",
  "上下逆転": "Top and bottom swap",
  "音の帯が揺れる": "The sound bars waver",
  "注意": "Warning",
  "危険": "Danger",
  "正常に戻る": "Back to normal",
  "警告色": "The warning colour",
  "L1 = 平常": "L1 = normal",
  "L2 = 注意": "L2 = warning",
  "L3 = 危険": "L3 = danger",
  "1k 到達": "Reaches 1k",
  "暗い配色へ": "To the dark palette",
  "明るい配色へ": "To the light palette",
  "12345 到達": "Reaches 12345",
  "吸う": "Breathe in",
  "吐く": "Breathe out",
  "負荷が上がる": "The load rises",
  "回復開始": "Recovery starts",
  "平常復帰": "Back to normal",
  "2 つへ分かれる": "It splits into two",
  "1 つへ集まる": "They gather into one",
  "捌ききれず溜まる": "More arrives than can be cleared",
  "弁を開ける": "Open the valve",
  "段ごとに絞られる": "It narrows at each stage",
  "2 つの道を通る": "It goes by two routes",
  "3 つへ同じ量ずつ配る": "Share it evenly across three",
  "全員へ同じものを写す": "Copy the same thing to everyone",
  "札の数だけ通す": "Let through as many as there are tokens",
  "急ぎを先に出す": "Send the urgent ones first",
  "予備へ倒れる": "It falls over to the standby",
  "落ちた分をもう一度試す": "Try the failed ones again",
  "満ちたら送る": "Send once it is full",
  "種類で分ける": "Split by kind",
  "落ちる分が増えて遮断する": "Failures build up and it cuts off",
  "写しで返す": "Answer from the copy",
  "そろった分だけ出す": "Send only what has come together",
  "重なりを消す": "Drop the duplicates",
  "古いものから押し出す": "Push the oldest out first",
  "時が過ぎた分が消える": "What has aged out disappears",
  "詰まって入口が絞られる": "It backs up and the entrance narrows",
  "割って札を貼り直す": "Split it and relabel",
  "番が来た分だけ出す": "Send only what its turn has come to",
  "鍵で行き先が決まる": "The key decides where it goes",
  "1 本にまとめて皆へ配る": "Merge into one and hand it to everyone",
  "送り主ごとに同じだけ出す": "Send the same amount for each sender",
  "やり直しの末に分かれる": "After the retries they part ways",
  "一度に一つだけ通す": "Let one through at a time",
  "流れを止めずに一部を控える": "Keep a copy of some without stopping the flow",
  "受け取りだけ先に返す": "Answer the receipt first",
  "部品の塗りの割合を 4 割で止める": "Stop the part's fill at 40%",
  "注文を受けてから出荷するまでの間に設備の稼働を置く": "Put the machine's running between taking the order and dispatch",
  "設備の稼働の右に受付を置き、受付の右に乾燥炉の温度を置く": "Put reception to the right of the machine's running, and the drying oven temperature to the right of reception",
  "1. 入ってくる": "1. It comes in",
  "2. 溜まる": "2. It builds up",
  "3. 送り出す": "3. Send it out",
  "4. 落ち着く": "4. It settles",
  "1. 受ける": "1. Take it",
  "2. 上層へ積む": "2. Stack it on the top layer",
  "3. 中層へ回す": "3. Pass it to the middle layer",
  "4. 底層から出す": "4. Send it out from the bottom layer",
  "1. 検査する": "1. Inspect it",
  "2. 2 つへ分かれる": "2. It splits into two",
  "1. 測る": "1. Measure it",
  "2. 記録へ集める": "2. Gather it into the record",
  "1. 部品の段で満ちる": "1. It fills on the part's phase",
  "2. 宿主の段で満ちる": "2. It fills on the host's phase",
  "3. 右だけ戻す": "3. Reset the right one only",
  "1. 注文が入る": "1. An order comes in",
  "2. 2 つの窓口へ分ける": "2. Split it across two desks",
  "3. 合流点へ渡す": "3. Hand it to the meeting point",
  "4. 1 つにまとめる": "4. Merge it into one",
  "1. 届く": "1. It arrives",
  "2. 3 つへ配る": "2. Hand it to three",
  "3. 控えへ渡す": "3. Pass it to the copy",
  "4. 3 つの控えへ写す": "4. Copy it to three replicas",
  "1. 中身を見る": "1. Look inside",
  "2. 種類で分ける": "2. Split by kind",
  "3. 注文だけ渡す": "3. Pass on the orders only",
  "4. 溜めてまとめて送る": "4. Hold them and send together",
  "1. 試す": "1. Try it",
  "2. 落ちた分を戻す": "2. Put the failed ones back",
  "3. 通った分を送る": "3. Send the ones that got through",
  "4. 予備へ倒れる": "4. Fall over to the standby",
  "2. 重なりを消す": "2. Drop the duplicates",
  "3. 残った分を送る": "3. Send what is left",
  "4. 満ちたら送る": "4. Send once it is full",
  "1. 問う": "1. Ask",
  "2. 写しで分かれる": "2. It parts at the copy",
  "3. 両方を送る": "3. Send both",
  "4. そろった分だけ出る": "4. Only what has come together leaves",
  "2. そろう": "2. They come together",
  "3. そろった分を送る": "3. Send what has come together",
  "4. 遮断する": "4. Cut it off",
  "2. 割れる": "2. It splits",
  "3. 溜める": "3. Hold it",
  "4. まとめて送る": "4. Send them together",
  "3. 積む": "3. Stack it",
  "4. 絞られる": "4. It narrows",
  "1. 両方届く": "1. Both arrive",
  "3. 置き場へ": "3. To the holding area",
  "4. 押し出される": "4. It gets pushed out",
  "2. 分かれる": "2. They part",
  "3. 置いておく": "3. Leave it there",
  "4. 時が過ぎる": "4. Time passes",
  "2. 鍵で偏る": "2. The key makes it lopsided",
  "3. 出口へ送る": "3. Send it to the exit",
  "4. 釣り合う": "4. It balances out",
  "2. 落ちる": "2. It fails",
  "3. 問い直す": "3. Ask again",
  "4. 相乗りする": "4. They share the ride",
  "1. ばらばらに届く": "1. They arrive out of order",
  "2. 番で分かれる": "2. They part by turn",
  "1. 送り主が並ぶ": "1. The senders queue up",
  "2. 交互に出る": "2. They leave in turn",
  "3. 並べ直しへ": "3. On to the reorder",
  "4. 番が来た分だけ出す": "4. Send only what its turn has come to",
  "1. 何度もやり直す": "1. Retry again and again",
  "2. 諦めた分が分かれる": "2. The ones given up on part ways",
  "2. 種類で分かれる": "2. They part by kind",
  "3. 戸へ向かう": "3. Head for the door",
  "4. 一度に一つだけ入る": "4. One goes in at a time",
  "1. 全部通る": "1. Everything gets through",
  "2. 一部を控える": "2. Keep a copy of some",
  "4. 受け取りだけ先に返す": "4. Answer the receipt first",
  "1. 左右から届く": "1. They arrive from both sides",
  "2. そろった分だけ出す": "2. Send only what has come together",
  "3. 頼まれる": "3. It is asked for",
};

/**
 * 開いている言語の段の題を返す。
 *
 * 日本語では題をそのまま出す (訳す前と 1 字も変えない)。
 * 英語では日本語を含む題だけ対訳を引き、引けなければ空にする。
 */
export function phaseTitle(title: string, locale: "ja" | "en"): string {
  if (locale === "ja") return title;
  if (!日本語を含む(title)) return title;
  return PHASE_TITLE_EN[title] ?? "";
}
