/**
 * カタログの見本 1 件ごとの字の英語 (#2461)。
 *
 * 名前は `i18n.ts` の `ITEM_NAME_EN` が持つ。 ここが持つのは **説明と変種の名前** の 2 つで、
 * どちらも日本語の側が見本の記法 (`topics/catalog/*.cdl.ts`) にある。
 *
 * **日本語の側をここに写さない**。 写すと記法を直した日に片方だけ古くなる。
 * 引く鍵は書き出し名 (説明) と日本語の名前 (変種) で、実物から導ける。
 *
 * **表に無い鍵は日本語のまま返さない**。 引けなかったことは検査が数える
 * (`catalog-item-en.test.ts` が実物の見本を走査して抜けを落とす)。
 */

/** 見本の説明。 鍵は記法の書き出し名 (`presetSwimlane` 等) */
export const ITEM_SUBTITLE_EN: Record<string, string> = {
  "abTestResult": "Draws arrows from the split to plan A and plan B, half each, and lines up the daily conversion rate and the winning share as parts (stacked-bar / donut)",
  "activityPolar": "Splits hours of activity by day of the week into weekday and weekend lanes, and shows them as wedges (polar-area)",
  "alertNotification": "Splits notices into four kinds — information, caution, error and success — and marks the chosen one by color and symbol (notification)",
  "arrayLineChart": "Draws the same run of numbers twice, once as a line with fill and once without (line-chart)",
  "arraySignalHistogram": "Splits a run of five numbers into a summary box and one box each, and also shows it as bars and as a list (array-bar / array-list)",
  "arrayStackedBar": "Compares two runs of numbers, group A and group B, with a total and mean box and with bars laid out across (stacked-bar)",
  "arrayWaterfall": "Splits gains and losses into separate lanes and shows them piling up to the closing balance as a phased diagram (waterfall)",
  "audioPlayer": "Builds a player readout of symbol, progress and mm:ss from a position slider and a playing toggle (media-player)",
  "badgePerPhase": "badge: switched phase by phase",
  "blockProduction": "How an Ethereum block comes to be",
  "blogArticlePreview": "Splits an article's thumbnail, heading and excerpt, and author and elapsed time into lanes, and gathers them onto one article card (article-preview)",
  "buildStatusTrafficLight": "Splits build status into red, amber and green lanes, and marks the chosen one with the three lamps of a traffic light (traffic-light)",
  "canvasMiniMap": "Moves a small window around the whole picture with a horizontal and a vertical slider (mini-map)",
  "chartBar": "Arrivals by channel",
  "chartGauge": "Progress against this period's revenue",
  "chartLine": "Response time week by week",
  "chartPie": "The breakdown of costs",
  "chartRadial": "Usage by feature",
  "chartSlope": "Applications by channel",
  "chartStackedBar": "The breakdown of contracts",
  "chartStat": "This month's churn rate",
  "chartWaffle": "Enquiries already handled",
  "checkoutCartSummary": "Works out the subtotal from the number of items in the cart, then joins it with arrows through the shipping fee to the total (cart-summary)",
  "checkoutCouponApply": "Joins three states of a discount code — not entered, entered and applied — with arrows, and shows how the discount badge appears (coupon-code)",
  "chessStartingBoard": "Splits 32 pieces into four rows — black's back rank, black's front rank, white's front rank and white's back rank — and shows the opening position on an 8×8 board (chess-board)",
  "cliTerminalSession": "Splits five commands into lanes for working with the repository, the change history and the development tools, and shows them on a terminal screen (terminal)",
  "clickToggle": "Pressing the target runs through the receiver and flips the pressed state",
  "colorPickerTheme": "The color picked in the color field reaches both a swatch box and its hexadecimal spelling",
  "commitDiffCounter": "Sets the number of added and deleted lines with plus and minus fields, and shows the balance as a +N / -N bar (diff-counter)",
  "contributionHeatmap": "Splits a year of activity into quarterly boxes with a total and a peak, and shows the 53-week by 7-day grid by shade (calendar-heatmap)",
  "cryptoWallet": "Splits four held assets into gainers and losers, and shows them as a list with a total (token-list)",
  "dashboardMetricsGrid": "Splits four figures — users, revenue, uptime and error count — into lanes, and shows them in a 2×2 grid (metrics-grid)",
  "dayScheduleTimeline": "Splits a day's plan into morning, afternoon and evening lanes, and shows it as a vertical run of times (timeline-vertical)",
  "decisionTree": "Branches in two on each yes or no answer until it reaches four outcomes, keeping parent and child at the same height so no arrow crosses a box",
  "deploySpinner": "Splits deployment status into running, done and failed, and shows the chosen one and its message with a turning ring (spinner)",
  "deviceBattery": "Splits battery level into bands below 20%, 20 to 60% and 60% and above, and shows the level set by the slider as a bar in ten segments (fuel-bar)",
  "dmReadReceipt": "Joins the three stages of a direct message — sent, delivered and read — with arrows, and marks them by the number and color of the ticks (read-receipt)",
  "docsBreadcrumb": "Joins four levels — home, docs, API and reference — with arrows, and marks where you are as the trail you followed (breadcrumb)",
  "docsTocNav": "Splits a document's table of contents into three lanes by indent depth, and marks the section being read (toc-nav)",
  "dynamicReadouts": "Shows sales and state values through four parts — a count up, a delta, a percentage ring and typed-out text (countup / delta / percent-ring / typewriter)",
  "edgeDeco": "Writing lanes to dress up the arrows",
  "edgeFlowBind": "Sets the thickness, the color and the position of the travelling dot on the arrow from sender to receiver with three fields — a slider, time and a choice",
  "edgeHead": "The five arrowhead shapes",
  "edgeRole": "Leaving out the role of the line",
  "edgeSide": "Leaving out the side the arrow leaves from",
  "eip1559Gas": "EIP-1559 — the fee rises and falls with congestion",
  "eip1559GasFlow": "Derives the fee of three blocks with formulas from a base and a priority fee slider, and shows the burned and the priority share as a stacked bar",
  "engineTachometer": "Splits engine speed into normal, cruising and over-revving bands, and shows the speed set by the slider on a 270° dial (circular-gauge)",
  "erc20Transfer": "An ERC-20 transfer — rewriting the balance table",
  "erc4337Flow": "ERC-4337 — making the wallet a contract so someone else can pay",
  "eventTargets": "Arrows, lanes and the whole diagram can receive actions too",
  "eventVariety": "Receives five kinds of action — a double press, a choice, losing focus, a key press and a long press — split into lanes for pressing, typing and touching",
  "examGrade": "Splits scores into five bands from A to F, and shows which band the score set by the slider falls into (grade)",
  "exemplarLoginFlow": "In lanes for the user, authentication and storage, follows five phases from the request through a first check and two-factor authentication to the reply, showing the number of successes, the rate and the response time as parts",
  "exemplarNotificationFlow": "In lanes for the sender, the delivery system and the receiving devices, follows five phases from a notice passing through the queue to arrival and a resend to the devices it never reached",
  "exemplarPaymentFlow": "In lanes for the buyer, the payment desk and the bank, follows four phases from purchase through identity checks and the bank's settlement to the ledger entry, showing the amount, the share verified and the status as parts",
  "featurePoll": "Splits the votes for four proposals into a lane for the leader and one for the rest, and shows them as bars with a total (poll-bar)",
  "feedbackThumbRating": "Splits votes for and against into two lanes, and shows the share as a green and a red band (rating-thumb)",
  "flowDirection": "Writes which way a flow runs (direction). Vertical stacks into one lane, horizontal makes one lane per actor. Writing a direction draws each arrow exactly between the ends as written",
  "formPasswordCheck": "Shows password strength on a four-segment meter and against three conditions, and gives the level its name in the same color (password-strength)",
  "formulaTextBind": "Takes the value typed into the input field and works out double and half with a formula, showing each in a box in the next lane",
  "funnelStages": "Narrowing down to an application",
  "ganttTimeline": "The steps up to release",
  "gitCommitList": "Splits five changes into a box per kind — feature, fix, docs, tidy-up and test — and shows them as a change history (commit-list)",
  "globalTimezoneClock": "Splits four cities in different time zones into lanes, and shows the local time in a grid of four columns (timezone-clock)",
  "gridLayoutMatrix": "Builds 12 boxes as a grid of 3 rows and 4 columns in one go, and lays them out in one lane per column (gridNodes)",
  "inputSliderBar": "The smallest sample where a value moved with a slider arrives, unchanged, in the description field of the box the arrow points to",
  "inputVariety": "Lines up four kinds of field — a range slider, a multiple choice, a toggle and text — and shows what was entered in a box (range / multi-select / tabs / text)",
  "interactiveOauthFlow": "Runs six arrows back and forth between the user, the authorization server and the resource server, with the server's delay set by a slider (OAuth)",
  "issuePriorityBadge": "Splits issue priority into high, medium and low, and shows the chosen one and its wording as a badge and a symbol (priority-badge)",
  "journeyMap": "Getting to a first use",
  "jwtAuth": "JWT auth (log in, issue a JWT, then reach the API with a bearer token)",
  "kindActor": "kind: actor (an outside party)",
  "kindCard": "kind: card (general information)",
  "kindEvent": "kind: event (an event log)",
  "kindFunction": "kind: function (a function call)",
  "kindStorage": "kind: storage (stored data)",
  "kpiBullet": "Shows which of three bands — poor, fair and good — the result falls into, and marks the gap to target with an arrow (bullet-chart)",
  "kpiDashboard": "Moving monthly revenue with a slider settles three figures — users, churn and recommendation — by formula, and lines four figures up",
  "kpiIconTile": "Splits three figures — growth, revenue and target — into lanes, and shows them as tiles with an icon (icon-tile)",
  "laneContain": "lane: contain (wrapped in a frame)",
  "laneGroup": "Bundles some of the lanes into one group and draws a frame around the bundled lanes and the boxes inside",
  "laneLifeline": "Draws a vertical dotted line down the middle of a lane (lifeline). Even a box shifted to another phase can be traced to its lane by the line",
  "laneMulti": "lane: three lanes, side by side",
  "laneSingle": "lane: one lane",
  "layoutOffset": "Shifts boxes, lanes and arrow labels from their automatic position by the amount written. The notation and the JSON are written differently and give the same diagram",
  "loginOtpVerify": "Takes the six-digit one-time code into six boxes and sends it for checking once they are full (otp-input)",
  "matrixHeatmap": "Splits hits and mistakes into a box per class and shows the 4×4 grid by shade (matrix)",
  "mindMap": "Making a diagram faster",
  "mixedTweenSet": "tween and set used together",
  "mlConfidenceMeter": "Splits inference confidence into bands below 40%, 40 to 74% and 75% and above, and shows which band the slider's value falls into (confidence-meter)",
  "monthCalendarView": "Splits a month into four weekly lanes, and shows it as a calendar grid of seven columns (calendar-month)",
  "nodeTone": "The six colors a box can take",
  "npsTrendKpi": "Splits the recommendation score (NPS) into this month's value, the change from last month and the trend, and gathers them onto one tile (kpi-trend-tile)",
  "numberSparkline": "Shows the value typed into the field two ways, as the current number and as a small line of the last 15 readings (sparkline)",
  "onboardingStepper": "Joins five stages from sign-up to first use with arrows, and marks the current one with a row of dots (step-indicator)",
  "opsAlertBanner": "Splits an operational notice into trigger, severity and response lanes, and shows it as a band whose color and symbol follow the severity (alert-banner)",
  "partInBox": "Writes a part name as a kind and places it as a box, then rewrites its state, scale and color number, puts it in a lane, joins an arrow to an element inside the part, splits an arrow to two parts, joins parts to each other, joins parts of different heights, gathers two parts into the same box, places one partway along the flow, lines them up with a name attached, and anchors a box to a part",
  "partsAchievement": "An achievement trophy, for an unlocked achievement",
  "partsAckFirst": "All 12 get an acknowledgement straight away, while only 5 have finished processing. When to reply and when to finish come apart",
  "partsAlarmClock": "An alarm clock, showing the alarm",
  "partsArcGauge": "An arc gauge, showing 0 to 100% along an arc",
  "partsBackpressure": "Once the queue piles to 100%, the sender is throttled from 100% to 40%. The outflow stays at 40% and does not move",
  "partsBadgeCount": "An unread badge, making the unread count stand out",
  "partsBandwidthMeter": "Bandwidth up and down, as an upload and download meter",
  "partsBarrierBox": "Twelve arrive from the left and seven from the right, and only the seven matched pairs leave. The five left over on the left wait for a partner",
  "partsBatchCollector": "Thirty arrive one at a time and leave in one go for every 10 collected. The right bar counts sends, not items",
  "partsBatteryLevel": "A battery level, read as a vertical fill",
  "partsBellNotification": "A notification bell, for a new alert",
  "partsBind2StateMirror": "bind: two states mirrored — binds independent states to a left and a right gauge in parallel",
  "partsBind5DigitCounter": "bind: a five-digit counter — five states tweening one digit each",
  "partsBindArcSweep": "bind: an arc sweep — one loading turn as the state runs 0 to 360",
  "partsBindCascade3": "bind: three states cascading — the state chain advances in turn as the phases split",
  "partsBindColorState": "bind: a color state — switches the fill straight from a string state",
  "partsBindComprehensive": "bind: the full story — a finished demo binding seven states over five phases onto three shapes",
  "partsBindCountdown": "bind: a countdown — tweens the state from high to low, with the time left in the subtitle",
  "partsBindCounterRadius": "bind: counter to radius — binds one state straight to a shape's radius",
  "partsBindEqualizer5": "bind: a five-bar equalizer — five independent states read as a music equalizer",
  "partsBindEscalation3": "Sets the alert level to 1, 2 and 3 across the phases, switching both the level number and the color",
  "partsBindGrid4": "bind: a 2×2 grid of four states — four tiles with independent states across lane and stack",
  "partsBindGrowShrink": "bind: grow then shrink — a rising then falling chain, read as breathing",
  "partsBindLevelColorCombo": "Applies two values, the water level and the fill color, to a single wave drawing",
  "partsBindModeToggle": "bind: a mode toggle — a light and dark toggle set from two states at once",
  "partsBindPulseCycle": "bind: a pulse cycle — a heartbeat built from an up and down tween chain",
  "partsBindRingCounter": "bind: a ring counter — an arc and a counter in the middle driven by the same state",
  "partsBindSplitFill": "bind: a split fill — two complementary states split one area into an upper and a lower part",
  "partsBindTemplateChain": "bind: a template chain — embeds {state} in both the title and the subtitle",
  "partsBindTweenChain4": "bind: a four-hop tween chain — chains 25% per phase across four phases",
  "partsBindWaveLevel2Phase": "bind: a wave level in two phases — binds the water level to a rise and then a fall",
  "partsBookmark": "A bookmark, read as saved",
  "partsBucketReservoir": "The water level in a container, a large wave inside a rectangle",
  "partsBudgetUsage": "Budget used, shown visually as consumption",
  "partsCacheBox": "Of 24 queries, 18 return from the local copy and only 6 travel all the way. Nothing is read twice",
  "partsCircleSizeRace": "A comparison by circle size, where the radius stands for strength",
  "partsCircuitBreaker": "Of 20, it cuts off where 6 have passed and 6 have failed, and refuses the remaining 8 without trying. What is refused never reaches the other side",
  "partsCloudSync": "Cloud sync, showing the progress of the sync",
  "partsCoinBalance": "A coin balance, with the currency live",
  "partsComparisonBars": "Bars that compare two values, A against B",
  "partsContentSorter": "Splits 20 into three by what they contain. With 11 orders, 6 enquiries and 3 others, the bars do not come out level",
  "partsCountdown": "A countdown arc, with the seconds falling",
  "partsCounterActor": "A count display, with the number live",
  "partsCountup": "A count up, with the number live",
  "partsDeadLetter": "Of 24, 21 pass on a retry and 3 go aside. Unlike the retry box, what is given up on does not return to the entry",
  "partsDedupeBox": "Keeps only the 18 seen for the first time out of 30, and drops the 12 that arrived twice. Fewer leave than arrive",
  "partsDigitalClock": "A digital clock, with hours and minutes live",
  "partsDiskUsage": "Disk usage, as an arc of how much is used",
  "partsDonut": "A breakdown ring, showing the share of each of several segments",
  "partsEdgeChain": "A chain of arrows, with three nodes activating in turn along the edges",
  "partsEvictBox": "Thirty arrive but only 10 fit. The remaining 20 are pushed out oldest first, so the newer ones stay",
  "partsExpBar": "An experience bar, for XP progression",
  "partsExpireBox": "Put 24 in and the 15 whose time has passed disappear on their own, leaving 9. The count falls with nobody removing anything",
  "partsFailoverSwitch": "The entry stays at 100% while the primary falls to 0% and the standby rises to 100%. The destination swaps rather than the flow splitting",
  "partsFairQueue": "Whether someone sent 30 or 6, the same 6 each leave. The heavy sender's remaining 24 wait for the next turn",
  "partsFanoutCopy": "The 100 published arrive as 100 at each of three receivers. Unlike the handing-out part, the total grows with the number of receivers",
  "partsFunnel3": "Narrows in three stages from top to bottom. Both the box width and the share remaining fall at each stage",
  "partsGaugeCluster": "Three gauges together, showing several figures at once",
  "partsHeartbeat": "A heartbeat trace, showing the pulse as a sparkline",
  "partsHorizontalBar": "A progress bar that grows across, filling from left to right",
  "partsKeyRouter": "Twenty-four are split by key and come out skewed, 18 against 6. The key decides the destination, so changing the ratio does not fix the skew",
  "partsKpiCard": "A KPI card, with a number, a delta and a small sparkline",
  "partsLikeButton": "A like button, with the count live",
  "partsLoadBalancer": "Hands 90 per second at the entry out to three exits at 30 per second each. The total is unchanged after handing out",
  "partsLocationPin": "A location pin, read as where you are now",
  "partsLockGate": "Eighteen arrive at once but only one may enter. The remaining 17 are kept, waiting at the door and entering in turn",
  "partsMailInbox": "A mail inbox, with an unread badge",
  "partsMergeJunction": "Gathers two entries into one exit. The total shows on the exit bar",
  "partsMessageBubble": "A message bubble, as in a chat",
  "partsMiniNetwork": "Shows two routes, an upper and a lower one, side by side from start to finish",
  "partsMotion": "Moves parts by phase while arrows stay joined, passes a value to what they join, names an element to move layer by layer, splits to two parts, gathers two parts into one box, puts a part that keeps its own phases next to one the host drives, joins a router's exit to a junction's entry, joins one exit of a load balancer to a copier to show the difference between splitting and copying, joins one exit of a sorter to a collector to show that only the split share piles up, joins the pass path of a retry loop to a switch's entry to show that a part with a return line can be built too, joins the keep path of a dedupe box to a collector to show that only the reduced share piles up, joins the two exits of a copy box to the left and right of a barrier box with two lines, and joins the barrier's matched share to a breaker to show a two-stage reduction",
  "partsMultiSparkline": "Three traces together, showing the trend of three figures at once",
  "partsNotification": "A notification card, in four kinds (information, warning, error and success)",
  "partsPercentRing": "A percentage ring, showing 0 to 100% as a ring",
  "partsPlayButton": "A play button, for media playback",
  "partsPriceCard": "A price card, with the price and its unit",
  "partsPriorityQueue": "Six urgent and eight normal items queue in one line, and the urgent ones leave first. The remaining eight are normal items still waiting",
  "partsProgressDots": "Progress dots, marking three completed stages",
  "partsProgressLong": "Six-stage progress, for a long wizard flow",
  "partsPulseIndicator": "A per-second count, as a rate display",
  "partsQueueDepth": "The gap between what comes in and what goes out piles up in the middle. Raising the service rate still leaves the backlog growing",
  "partsRadar": "A radar chart, for seeing where the strengths lean across several axes",
  "partsRainbowStack": "Five rainbow tiers, a stack in five tones",
  "partsRateLimiter": "Of 16 arrivals, lets through the 10 that the 10 tokens cover and refuses the remaining 6",
  "partsRatingStars": "A star rating, filled out of five",
  "partsReorderBox": "Twenty arrive out of order, and only the 12 whose turn has come leave. The 8 waiting for an earlier turn are kept, not dropped",
  "partsRetryLoop": "Three of 12 fail, and retrying those three brings the passing side back to 12. What fails returns to the earlier stage",
  "partsSaleTag": "A sale tag, badging the discount rate",
  "partsSampleTap": "All 16 travel on without loss, and a copy of 3 of them stays behind as a sample. Unlike the sorter, the main line does not shrink",
  "partsSearchBar": "A search field, read as an input area",
  "partsShoppingCart": "A shopping cart, with the item count live",
  "partsSingleFlight": "Twenty-four identical queries collapse into two that travel on, and the answer that comes back is handed to all 24. They are made to wait rather than dropped",
  "partsSparkline": "A small line chart, for the trend of past numbers",
  "partsSpeedometer": "A speedometer, showing speed with a needle on an arc",
  "partsSplitBox": "Three large parcels break into 24 small ones, and the labels grow to 24 as well. More leave than arrive",
  "partsSplitRouter": "Splits one entry into two exits. The split share shows on both bars",
  "partsStackedLayer": "A bar of stacked layers, for the breakdown of a total",
  "partsStateIndicator": "A state indicator, showing the state by the color of one large shape",
  "partsStatusDot": "A dot that marks the state, shown by a small colored dot",
  "partsStatusTimelineWeek": "A weekly status timeline, as seven days of state bands",
  "partsStepProgress": "Progress through a procedure, as numbered wizard steps",
  "partsThermometer": "A thermometer, reading a continuous value as a vertical bar",
  "partsTimelineStrip": "A timeline strip, as a band of statuses in time order",
  "partsToggleSwitch": "An on and off switch, showing which state it is in",
  "partsTrafficLightStack": "A three-lamp traffic light, showing the state with stacked circles",
  "partsUserAvatar": "A user icon, drawn as a large circle",
  "partsValveFlow": "How far the middle valve opens decides how much passes to the exit",
  "partsVolumeMeter": "A volume meter, read as loudness",
  "partsWaveGauge": "A rectangular gauge with a wave, read as a liquid level",
  "partsWeatherIcon": "A weather icon, showing the condition by color",
  "partsWifiSignal": "A Wi-Fi signal, in five strengths",
  "pathProgressDemo": "Shows the slider's progress as the filled part of a bent line and as a percentage ring, with a done mark at 100% (path-progress)",
  "patternBranch": "pattern: Branch (a conditional fork)",
  "patternDirect": "pattern: Direct (straight to the neighbouring node)",
  "patternEmit": "pattern: Emit Event (a notice to the outside)",
  "patternFanIn": "pattern: Fan-in (several workers gathered)",
  "patternFanOut": "pattern: Fan-out (one input to several workers)",
  "patternLoop": "pattern: Loop (repeated work)",
  "patternPassthrough": "pattern: Passthrough (straight through a relay node)",
  "patternRollback": "pattern: Rollback (unwound on failure)",
  "patternSchedule": "pattern: Schedule (run on a timer)",
  "patternValidateProcess": "pattern: Validate then Process (checked before the work)",
  "perfBubbleChart": "Splits five operations into lanes above and below a load of 7, and compares them by circle size on three axes (bubble-chart)",
  "playerLeaderboard": "Splits six players into the top three, the middle two and one outside the view, and shows the top five as a ranking (leaderboard)",
  "playlistSongQueue": "Splits five queued songs into played, playing and next lanes, and highlights the one set by plus and minus fields (song-queue)",
  "portfolioDonut": "Puts stocks and bonds under traditional assets and cash and crypto under alternatives, showing the split as a ring (donut)",
  "postReactionPoll": "Splits the votes for three emoji — like, love and celebrate — into lanes, and shows them as a reaction part (quick-poll-emoji)",
  "postReactions": "Splits four kinds of reaction on a post into one lane per emoji, and shows them as a row of badges (reaction-bar)",
  "presetChartLine": "A line chart showing how a series moves over time",
  "presetChartPie": "A pie chart showing each share of the whole",
  "presetClassDiagram": "A UML class diagram showing the six kinds of relationship between classes",
  "presetEr": "A diagram of the relationships between tables",
  "presetFlow": "A diagram that shows the order of work as one line from left to right",
  "presetFlowchart": "A diagram of a process with branches and decisions",
  "presetFunnel": "A narrowing diagram that shows the drop-off at each stage",
  "presetGantt": "A schedule that shows task spans and dependencies as horizontal bars",
  "presetInfrastructure": "A diagram that shows a cloud and network layout in layers",
  "presetMindMap": "A diagram that spreads ideas out from a central topic",
  "presetNetwork": "A diagram of how network devices and segments connect",
  "presetQuadrant": "A diagram that splits items into four quadrants on two axes to set priority",
  "presetSequence": "A diagram that lays exchanges out over time on vertical timelines",
  "presetStateMachine": "A diagram of states and the conditions for moving between them",
  "presetStateMachine2": "A nested state diagram with hierarchical states and transition actions",
  "presetSwimlane": "A diagram that splits work into one lane per role to show the flow",
  "presetTopology": "A diagram that shows a system's components and links by their placement",
  "presetTree": "An org chart or tree that shows parent and child in vertical levels",
  "presetUserJourney": "A diagram that shows how the user's feeling shifts step by step",
  "priceCandlestick": "Splits eight days of opening and closing prices into lanes for up days and down days, and shows them as candlesticks (candlestick)",
  "prodLogTail": "Splits the last five lines of the production record into time, severity and body lanes, and colors the badge by information, caution or error (log-stream)",
  "productPriceTag": "Sets the new price with plus and minus fields, works out the discount from the old price, and gathers the three values onto a price tag (price-tag)",
  "productRating": "Splits product ratings into bands of 0 to 1.5, 2 to 3.5 and 4 to 5, and marks the rating set by the slider as a number of stars (rating)",
  "profileAvatarUpload": "Joins three states — nothing chosen, an image dropped, and the image shown cropped to a circle — with arrows, and shows the drop area (file-dropzone)",
  "projectGantt": "Hands four stages — design, build, test and release — along with arrows, and shows their spans as a bar schedule (gantt)",
  "publishWorkflowSteps": "Joins four stages — draft, check, approval and publish — with arrows, and shows the progress of the publishing procedure (step-progress)",
  "quadrantMatrix": "The order to start in",
  "radialHubAndSpoke": "Sends arrows out from a central box in four directions at 0°, 90°, 180° and 270°, splitting them into an upper and a lower lane so no arrow crosses a box",
  "radioSelect": "Picks exactly one of low, medium and high (radio) and shows the chosen step as a box and a number",
  "readoutVariety": "Shows temperature and state values through three parts — a shaded cell, a number badge and a colored dot (heat-cell / badge / status-dot)",
  "relativePos": "Writes position as a direction and gap from another box rather than as coordinates. Right, left, up and down can be written",
  "renderOffsetDrift": "Puts a fixed reference point next to one whose drawn position alone is shifted by a horizontal and a vertical slider (renderOffset)",
  "repeatDeriveChain": "Declares N rectangles with repeatNodes and deriveChain, passing each value on to the next",
  "resourceTreemap": "Splits six departments' budgets into lanes for 15% and above, 5 to 14% and below 5%, and compares them by area (treemap)",
  "revenueKpiCard": "Marks the difference between last period and this one with an arrow, and shows it together with six months of trend on one card (kpi-card)",
  "revenueScoreboard": "Moves current revenue with a slider and shows the gap to the third-quarter target in large figures (number-board)",
  "reviewerStack": "Splits seven reviewers into the five shown and the two remaining, and shows them as overlapping circles (user-stack)",
  "richLayeredPriorityFee": "A three-layer priority fee, where congestion moves the base, the priority and the cap together",
  "richOrderStatusFlow": "Order states in an online shop (received, paid, dispatched, delivered, done)",
  "richPipelineDemo": "Progress through a five-stage CSV pipeline",
  "richScoreLeaderboard": "How four players' scores move (the ranking changes over four rounds, and circle size stands for strength)",
  "richServerLoadDashboard": "CPU load on four servers (a morning peak, a steady midday, an evening scale-down and an idle night)",
  "roomThermometer": "Splits room temperature into bands below 15°C, 15 to 25°C and 25°C and above, and shows the temperature set by the slider as a vertical bar (thermometer)",
  "saasPricingTier": "Splits three price plans — starter, standard and enterprise — into lanes, and compares their name, price and benefits side by side (pricing-tier)",
  "salesFunnel": "Joins four stages — visit, sign-up, trial and purchase — with arrows, and shows the head count falling at each step as a funnel (funnel)",
  "sceneAuditFlow": "scene: an audit (auditor to the books to the regulator)",
  "sceneBankingFlow": "scene: a bank transfer (ATM to bank to online shop)",
  "sceneCompliance": "scene: meeting a regulation (regulator to the books to bank)",
  "sceneCryptoTransfer": "scene: a crypto transfer (wallet to exchange to chain)",
  "sceneEcOrder": "scene: an online order (customer to shop to warehouse)",
  "sceneFactoryLine": "scene: a factory assembly line (robot to sensor to database)",
  "sceneIotOnchain": "scene: from an IoT device to the ledger (sensor to RPC to contract)",
  "sceneLegalNotarization": "scene: legal work (lawyer to notary to the register)",
  "sceneNftMarketplace": "scene: an NFT sale (buyer to marketplace to NFT)",
  "sceneNotification": "scene: a notification (message to service to app)",
  "scenePaymentSettlement": "scene: settlement (provider to card network to bank)",
  "sceneStockTrading": "scene: securities trading (trader to brokerage to exchange)",
  "sceneSupportFlow": "scene: a support enquiry (support to ticket to development)",
  "sceneTrustAsset": "scene: a trust asset (trader to trust bank to the books)",
  "scoreSlope": "Splits five people into lanes for those who rose and those who fell, and shows it as the slope joining before and after (slope)",
  "scrollNarrative": "Turns how far the page has been scrolled into a single value, and three boxes show the same progress",
  "searchResults": "Splits five search results into lanes for documents and for the hands-on playground, and shows the title, an excerpt and the location (search-result)",
  "serverEventLog": "Splits five operational events into information, detail, caution and error lanes, and shows them as a record in time order (event-log)",
  "serverUptimeStatus": "Splits six spans of the uptime record into up, standby and down lanes, and shows each span as a colored band (status-timeline)",
  "serviceHealthGrid": "Splits six services into up, degraded and down lanes, and shows them as a green, amber and red grid (service-health)",
  "setSwitch": "set: switched at once, with no interpolation",
  "shapeApiGateway": "shape: api-gateway (gate posts with an arch and a traffic arrow)",
  "shapeArcSweep": "Lines up arcs of 0°, 90° and 180°, and moves only the fourth with a slider for comparison (dyn-arc)",
  "shapeAtm": "shape: atm (a cash machine with a card slot and a cash dispenser)",
  "shapeAuditor": "shape: auditor (an auditor with a magnifier and a check)",
  "shapeBitcoinChain": "shape: bitcoin-chain (₿, proof of work, orange)",
  "shapeBlockchainBlock": "shape: blockchain-block (three linked blocks with a hash pointer)",
  "shapeBrokerage": "shape: brokerage (a brokerage tower with a candle chart and an up arrow)",
  "shapeCdnEdge": "shape: cdn-edge (a globe with five edge nodes and an arc)",
  "shapeChainFill": "Three dyn-rects side by side, where a base slider moves each fill together through formulas",
  "shapeCirclePulse": "Lines up rings at 0%, 33% and 66%, and moves only the fourth with a slider for comparison (dyn-circle)",
  "shapeCloud": "shape: cloud (five circles combined, for a cloud or SaaS)",
  "shapeCylinder": "shape: cylinder (for a database or storage)",
  "shapeDiamond": "shape: diamond (for a decision)",
  "shapeEthereumChain": "shape: ethereum-chain (Ξ, proof of stake, purple)",
  "shapeExchange": "shape: exchange (a trading venue, swapping $ and Ξ)",
  "shapeFile": "shape: file (a rectangle with a folded corner, for a file or document)",
  "shapeFolder": "shape: folder (a rectangle with a tab, for a folder or package)",
  "shapeGear": "shape: gear (for settings or a processing engine)",
  "shapeHexagon": "shape: hexagon (for a component or service)",
  "shapeIotSensor": "shape: iot-sensor (an IoT beacon sending a signal)",
  "shapeLawyer": "shape: lawyer (a lawyer with a wig and scales)",
  "shapeMessageBubble": "shape: message-bubble (a rounded rectangle with a tail)",
  "shapeMobileDevice": "shape: mobile-device (a handheld device)",
  "shapeNft": "shape: nft (a frame with polygonal art and a verified badge)",
  "shapeNotary": "shape: notary (a notary with a scholar's hat and a seal)",
  "shapeOrient": "The four directions a shape can fill from",
  "shapePaymentProvider": "shape: payment-provider (a POS terminal with a screen and keypad)",
  "shapePerson": "shape: person (a human figure, for an actor or user)",
  "shapePolyRotate": "Lines up polygons with 3, 6 and 8 corners, and turns and resizes only the fourth, a hexagon, with sliders (dyn-polygon)",
  "shapeRectFill": "Lines up squares filled 25%, 50% and 75%, and moves only the fourth with a slider for comparison (dyn-rect)",
  "shapeRegulator": "shape: regulator (a regulator with a crown and a badge)",
  "shapeRobotArm": "shape: robot-arm (an industrial machine arm)",
  "shapeSatellite": "shape: satellite (for edge communication)",
  "shapeServerRack": "shape: server-rack (a 19-inch rack, for a physical server)",
  "shapeSmartContract": "shape: smart-contract (a contract plus a gear, for automatic execution)",
  "shapeStack": "shape: stack (stacked rectangles, for layers or history)",
  "shapeTerminal": "shape: terminal (a CLI shell, a mac title bar plus a prompt)",
  "shapeCodeBlock": "shape: code-block (a snippet, an editor tab plus four syntax lines)",
  "shapeNetworkNode": "shape: network-node (a network hub, a router or switch)",
  "shapeStorefront": "shape: storefront (a physical shop with an awning, a door and windows)",
  "shapeToken": "shape: token (a coin, for fungible currency)",
  "shapeTrader": "shape: trader (a trader with a headset and a laptop chart)",
  "shapeTrustBank": "shape: trust-bank (a bank facade with a crown, for entrusted trust)",
  "shapeWallet": "shape: wallet (a purse with coins and a balance display)",
  "shapeWarehouse": "shape: warehouse (a roof with a shutter and boxes)",
  "shapeWaveTank": "Lines up waves at 25%, 50% and 75% water level, and moves only the fourth with a slider for comparison (dyn-wave)",
  "shapeWindow": "shape: window (a GUI application, traffic lights plus a body)",
  "shippingOrderStatus": "Joins four stages — packing, dispatch, in transit and delivered — with arrows, and marks the stage set by plus and minus fields on a band of symbols (order-status)",
  "signupFormSummary": "Splits five sign-up fields into lanes for the person, the contact details and the preferences, and shows what will be sent as a list of names and values (form-summary)",
  "skillRadar": "Splits five skills into lanes for 7 and above, 5 to 6 and below 5, and shows the shape with a polygon part (radar)",
  "socialShareButtons": "Splits the four places an article was shared to into lanes, and shows them as a row of buttons with a share count (share-buttons)",
  "sprintChecklist": "Splits six tasks into done and not-done lanes, and shows the progress as a ticked list (checklist)",
  "sprintKanbanBoard": "Splits six tasks into to-do, in-progress and done lanes, and shows them as a kanban board (kanban-board)",
  "stackPair": "stack: two rows",
  "stackTriple": "stack: three rows",
  "startupOrgChart": "Splits three levels — a president, two managers and three staff — into lanes, and joins each leader to those they lead with an arrow (org-chart-mini)",
  "stateActive": "edge: a moving state",
  "stateInactive": "edge: a stopped state",
  "stateStartEnd": "Writes the start and the end of a state diagram on boxes (initial / final). A diagram that leaves them out takes the first and last of the sequence",
  "stepperControl": "Shows the count set with a plus and minus field (stepper) in two places, a bar and a number",
  "styleDottedFlow": "dotted-flow style (a dotted line with particles, for a moving flow)",
  "styleSolid": "solid style (a solid line with an arrowhead, the default for an edge)",
  "supportChat": "Splits five support messages into a user lane and a desk lane, and shows them as an exchange of speech bubbles (chat-bubble)",
  "taskProgressGroup": "Splits four tasks into lanes for 50% and above and below, and lines their progress up in one part (progress-group)",
  "teamActivityFeed": "Joins five people's events newest first with arrows, and shows them as a recent activity list (activity-feed)",
  "teamAttendanceGrid": "Splits four people into lanes, and shows five days by four people of attendance as a grid (attendance-grid)",
  "teamKpiComparison": "Splits two teams' pace into an upper and a lower band, and compares them by marking the gap with an arrow (kpi-comparison)",
  "teamPresenceStatus": "Splits five people into present, away and out lanes, and shows presence as a colored dot (user-presence)",
  "teamThreadSummary": "Splits a thread's unread count, participants, latest speaker and elapsed time into lanes, and gathers them into a one-line summary (thread-summary)",
  "techPills": "Splits five technologies into lanes for the screen, the platform and the build, and shows them as a row of pills (pill-group)",
  "techTagCloud": "Splits eight technologies into lanes for usage of 20 and above, 10 to 19 and below 10, and shows their weight by word size (tag-cloud)",
  "textDslActorKeys": "Writing a box's field names in English",
  "textDslC4": "A C4 diagram of an online order",
  "textDslClass": "The relationships between classes",
  "textDslCode": "Calls, writes and events",
  "textDslEr": "The design of tables and their relationships",
  "textDslErMesh": "Two many-to-many pairs, in 8 tables and 8 relationships",
  "textDslFlow": "The authentication flow",
  "textDslGantt": "An example of writing a quarterly plan",
  "textDslMind": "Ideas branching out",
  "textDslPie": "An example of writing a breakdown by share",
  "textDslRowMarkKeys": "Writing rows and marks in English",
  "textDslSequence": "An example of writing an exchange over time",
  "textDslStateMachine": "The states of authentication",
  "textDslStateMarks": "The states of an order",
  "textDslSwimlane": "Work run at the same time",
  "textDslFlowchart": "Approving an expense claim",
  "textDslTopology": "The layout of a system",
  "textDslValueKeys": "Writing the value and the previous value in English",
  "textDslValues": "An example of writing relationships between values",
  "timelineDrive": "Derives the length of a bar and the angle of an arc with formulas from a single time value that repeats every 3 seconds (timeline)",
  "timerStopwatch": "Builds a mm:ss.ms readout from two values, the seconds elapsed and whether it is running (stopwatch)",
  "tokenTransferSolidity": "An ERC-20 transfer (one lane per kind)",
  "toneAccent": "accent tone (the leading color, dark navy)",
  "toneError": "error tone (red, for an error state)",
  "toneInfo": "info tone (light blue, for information)",
  "toneSuccess": "success tone (green, for a successful state)",
  "toneTeal": "teal tone (blue green, for secondary emphasis)",
  "toneWarning": "warning tone (orange, for a warning state)",
  "tournamentPodium": "Puts first place in the middle, second on the left and third on the right, and shows a podium of three steps of different heights (podium)",
  "trafficSankey": "Shows, as band thickness, how many people come from search, social and direct traffic through the entry and product pages to a purchase (sankey)",
  "treeHierarchy": "How the package is put together",
  "tutorialVideoCards": "Splits three tutorial videos into one lane per language, and shows them as a list of thumbnails (video-card)",
  "tweenChain": "tween: accumulated across successive phases",
  "tweenSimple": "tween: a straight interpolation between numbers",
  "userAvatar": "Takes the initial of each word of the name entered and draws it on a blue circle as the user's mark (avatar)",
  "userVenn": "Splits two groups, users and payers, into three regions — users only, both, and payers only — to show the overlap (venn)",
  "viewportSpacing": "Changes the gap between lanes, the gap between boxes, the label padding, the lane width, the diagram size and the scale one at a time in the whole-diagram field (viewport)",
  "visualBindBar": "Applies one value to the width of a horizontal bar and the height of a vertical one, and shows the same value as a number (wBind / hBind)",
  "visualBindOpacity": "Puts a box whose density changes with the slider next to one that is given no value and never changes, for comparison (opacity)",
  "voiceMessagePlayback": "Splits sender, waveform and playback into lanes, showing loudness as bar height and the played position by bar color (voice-message)",
  "weekCalendarView": "Splits a week into seven lanes, one per day, and shows it as this week's calendar (calendar-week)",
  "weekWeather": "Splits five days of weather into lanes for sun, cloud and rain, and storms, and shows them as a five-day forecast (weather-forecast)",
  "worldMapPins": "Splits five cities into lanes for Asia and the Pacific and for Europe and the Americas, and places them as pins on a flat world map (map-pin)",
  "xypadNavigate": "Shows which quadrant — top left, top right, bottom left or bottom right — the point picked on a flat pad (xypad) falls into",
  "yearRoadmap": "Splits a year's plan into four quarterly lanes, stacks each quarter's items, and hands one quarter to the next with an arrow (roadmap)",
};

/**
 * 変種の名前。 鍵は日本語の名前そのもの。
 *
 * 変種の名前は書き出し名の末尾 (`pattern__<元>__<名>`) と `patternBase__<元>` の 2 か所に
 * 現れるが、同じ語は同じ訳でよいので 1 つの表で受ける。
 */
export const PATTERN_NAME_EN: Record<string, string> = {
  "1 つの関係": "One relationship",
  "1 件": "One entry",
  "1行にまとめて書く": "Written on one line",
  "2つの組": "Two pairs",
  "4割で伸ばし終える": "Finishes growing at 40 percent",
  "5つの気持ち": "Five moods",
  "main": "main",
  "ずらさない": "No offset",
  "そろってから先に返す": "Replies first once all have arrived",
  "そろってから押し出す": "Pushes out once all have arrived",
  "そろってから遮断する": "Cuts off once all have arrived",
  "まとめた間隔": "One gap for all",
  "やり直してから倒す": "Retries, then gives up",
  "ゆっくり数える": "Counts up slowly",
  "よけてから溜める": "Steps aside, then queues",
  "クラス図で書く": "Written as a class diagram",
  "フローで書く": "Written as a flow",
  "上": "Up",
  "上に置く": "Placed above",
  "下": "Down",
  "下に置く": "Placed below",
  "並べる": "Side by side",
  "今だけ": "Now only",
  "仕分けてから溜める": "Sorts, then queues",
  "倍率": "Scale",
  "倍率を変える": "Change the scale",
  "値のまま描く": "Drawn as the raw value",
  "先端の塗り": "Fill at the head",
  "先端の多重度": "Multiplicity at the head",
  "先端の矢じり": "Arrowhead at the head",
  "写してから待ち合わせる": "Copies, then waits for the rest",
  "分ける": "Split",
  "別の状態で色を引く": "Color taken from another state",
  "前と今": "Before and now",
  "前の値つき": "With the previous value",
  "前後つき": "With before and after",
  "割ってから溜める": "Splits, then queues",
  "割ってから詰まらせる": "Splits, then jams",
  "右": "Right",
  "右に置く": "Placed right",
  "名前だけ": "Name only",
  "名前で描く": "Drawn by name",
  "名前のまま描く": "Drawn as the name",
  "名札で描く": "Drawn by label",
  "名札の余白": "Label padding",
  "問い合わせを一人ずつ通す": "Lets queries through one at a time",
  "図の広さ": "Diagram size",
  "多重度を全て並べる": "All multiplicities laid out",
  "左": "Left",
  "左に置く": "Placed left",
  "帯だけ": "Band only",
  "引かない": "No line",
  "引く": "Line drawn",
  "振り分けて合流させる": "Splits out, then merges back",
  "接点つき": "With touchpoints",
  "控えを取っても束は変わらない": "Taking a copy leaves the bundle unchanged",
  "文字の入力": "Text input",
  "既定の時間": "Default duration",
  "既定の速さ": "Default speed",
  "日時の入力": "Date and time input",
  "日本語で書く": "Written in Japanese",
  "書いた端のとおりに繋ぐ": "Joined exactly as written",
  "書かない": "Left out",
  "書く": "Written",
  "札に色を付けない": "No color on the label",
  "札の字で色を引く": "Color taken from the label text",
  "根元の塗り": "Fill at the tail",
  "根元の多重度": "Multiplicity at the tail",
  "根元の矢じり": "Arrowhead at the tail",
  "横に並べる": "Laid out across",
  "段を分けて書く": "Written as separate phases",
  "気持ちだけ": "Mood only",
  "流れに沿って動かす": "Moves along the flow",
  "流れの途中に置く": "Placed partway along the flow",
  "状態を上書き": "State overwritten",
  "矢印の名前をずらす": "Arrow labels offset",
  "矢印を分ける": "Arrows split",
  "矢印を繋ぐ": "Arrows joined",
  "矢印を集める": "Arrows gathered",
  "箱の間": "Gap between boxes",
  "箱をずらす": "Boxes offset",
  "簡単": "Simple",
  "線の色を付ける": "Line color set",
  "線の色を書かない": "No line color",
  "縦に積む": "Stacked vertically",
  "縦列に置く": "Placed in a lane",
  "縦列の幅": "Lane width",
  "縦列の間": "Gap between lanes",
  "縦列をずらす": "Lanes offset",
  "縦列を書かない": "No lanes",
  "縦列を書く": "Lanes written",
  "縦列を束ねる": "Lanes bundled",
  "繋ぐ要素を名指しする": "Names the element to join",
  "色の欄で書く": "Written in the color field",
  "色番号を変える": "Change the color number",
  "色調の欄で書く": "Written in the tone field",
  "英語で書く": "Written in English",
  "落ちた分が消える": "What drops off disappears",
  "落ちた分が相乗りする": "What drops off rides along",
  "複数": "Several",
  "複雑": "Complex",
  "要素ごとに繋ぐ": "Joined per element",
  "見出しだけ": "Heading only",
  "説明つき": "With a description",
  "速さを選ぶ": "Pick the speed",
  "部品どうしを繋ぐ": "Parts joined to each other",
  "部品の段を残す": "Keeps the part's phases",
  "部品を基準にする": "Anchored to a part",
  "配ってから写す": "Hands out, then copies",
  "重なりを消してから溜める": "Clears the overlap, then queues",
  "釣り合わせてから順に戻す": "Balances, then returns in order",
  "鍵の偏りを釣り合わせる": "Balances a skewed key",
  "間隔を書かない": "No gap written",
  "集める": "Gathered",
  "順に戻してから溜める": "Returns in order, then queues",
  "題も書く": "Title written too",
  "高さの違う部品どうしを繋ぐ": "Parts of different heights joined",
};
