/**
 * Preset SSOT — cdl の 20 preset を metadata で export。
 *
 * diagram 本体は src/topics/presets.cdl.ts で cdl の高位 API (swimlane / flow / topology 等)
 * で構築、 本 file では列挙 + metadata (eyebrow / title / subtitle / tags / docHref) を持つ。
 *
 * PresetCard / PresetDetail / PresetGrid 全てで本 SSOT を参照。
 */
import type { CdlDiagram } from "@cardenelabs/cdl";
import {
  presetSwimlane,
  presetFlow,
  presetSequence,
  presetTopology,
  presetEr,
  presetStateMachine,
  presetInfrastructure,
  presetClassDiagram,
  presetTree,
  presetUserJourney,
  presetMindMap,
  presetMindMapRadial,
  presetFunnel,
  presetQuadrant,
  presetChartPie,
  presetChartLine,
  presetGantt,
  presetFlowchart,
  presetNetwork,
  presetStateMachine2,
} from "@/topics/presets.cdl";

export interface PresetMetadata {
  id: string;
  slug: string;
  eyebrow: string;
  title: string;
  subtitle: string;
  tags: string[];
  docHref: string;
  diagram: CdlDiagram;
}

export const PRESETS: PresetMetadata[] = [
  {
    id: "swimlane",
    slug: "swimlane",
    eyebrow: "SWIMLANE / LAYOUT",
    title: "swimlane",
    subtitle: "3 lane 自動配置。 laneId(label) で slug 参照、 lane.x を auto-layout。",
    tags: ["3 lane", "auto layout"],
    docHref: "/docs/cdl/presets/swimlane",
    diagram: presetSwimlane,
  },
  {
    id: "flow",
    slug: "flow",
    eyebrow: "FLOW / SEQUENCE",
    title: "flow",
    subtitle: "1 lane sequence。 前 step → 次 step 自動 edge、 縦 stack。",
    tags: ["1 lane", "sequential"],
    docHref: "/docs/cdl/presets/flow",
    diagram: presetFlow,
  },
  {
    id: "sequence",
    slug: "sequence",
    eyebrow: "SEQUENCE / UML",
    title: "sequence",
    subtitle: "actor 列 × 時系列 row。 UML sequence diagram 風、 return 動作あり。",
    tags: ["actor", "UML"],
    docHref: "/docs/cdl/presets/sequence",
    diagram: presetSequence,
  },
  {
    id: "topology",
    slug: "topology",
    eyebrow: "TOPOLOGY / DEPLOY",
    title: "topology",
    subtitle: "group + container 配置。 構成図 / deployment diagram 風。",
    tags: ["group", "container"],
    docHref: "/docs/cdl/presets/topology",
    diagram: presetTopology,
  },
  {
    id: "er",
    slug: "er",
    eyebrow: "ER / DB SCHEMA",
    title: "er",
    subtitle: "entity + cardinality。 ER 図 / DB schema 風、 relation 表現。",
    tags: ["entity", "relation"],
    docHref: "/docs/cdl/presets/er",
    diagram: presetEr,
  },
  {
    id: "stateMachine",
    slug: "state-machine",
    eyebrow: "STATE / FSM",
    title: "stateMachine",
    subtitle: "state + transition trigger。 FSM / workflow 図風。",
    tags: ["state", "transition"],
    docHref: "/docs/cdl/presets/state-machine",
    diagram: presetStateMachine,
  },
  {
    id: "infrastructure",
    slug: "infrastructure",
    eyebrow: "INFRA / ARCHITECTURE",
    title: "infrastructure",
    subtitle: "SaaS architecture、 web + api + db + cache の tier 構成。",
    tags: ["saas", "arch"],
    docHref: "/docs/cdl/presets/infrastructure",
    diagram: presetInfrastructure,
  },
  {
    id: "classDiagram",
    slug: "class",
    eyebrow: "CLASS / UML",
    title: "classDiagram",
    subtitle: "class + attribute + relation。 UML クラス図風、 aggregates / extends。",
    tags: ["class", "UML"],
    docHref: "/docs/cdl/presets/class",
    diagram: presetClassDiagram,
  },
  {
    id: "tree",
    slug: "tree",
    eyebrow: "TREE / ORG CHART",
    title: "tree",
    subtitle: "組織図 / hierarchy tree。 root → branch 縦展開。",
    tags: ["hierarchy", "org"],
    docHref: "/docs/cdl/presets/tree",
    diagram: presetTree,
  },
  {
    id: "userJourney",
    slug: "user-journey",
    eyebrow: "USER JOURNEY",
    title: "userJourney",
    subtitle: "Signup / Onboarding 等の step 別 emotion / touchpoint。",
    tags: ["ux", "journey"],
    docHref: "/docs/cdl/presets/user-journey",
    diagram: presetUserJourney,
  },
  {
    id: "mindMap",
    slug: "mind",
    eyebrow: "MIND MAP / IDEA",
    title: "mindMap",
    subtitle: "root + branch 放射。 idea / brain storm 図風。",
    tags: ["mind map", "brain storm"],
    docHref: "/docs/cdl/presets/mind",
    diagram: presetMindMap,
  },
  {
    id: "mindMapRadial",
    slug: "mindmap-radial",
    eyebrow: "MIND MAP / RADIAL",
    title: "mindMapRadial",
    subtitle: "center → 8 方向。 中心軸型 concept map、 対称配置。",
    tags: ["radial", "8-way"],
    docHref: "/docs/cdl/presets/mindmap-radial",
    diagram: presetMindMapRadial,
  },
  {
    id: "funnel",
    slug: "funnel",
    eyebrow: "FUNNEL / CONVERSION",
    title: "funnel",
    subtitle: "Visit → Signup → Purchase の conversion funnel。",
    tags: ["metric", "conversion"],
    docHref: "/docs/cdl/presets/funnel",
    diagram: presetFunnel,
  },
  {
    id: "quadrant",
    slug: "quadrant",
    eyebrow: "QUADRANT / MATRIX",
    title: "quadrant",
    subtitle: "2x2 マトリクス、 impact vs effort 型の decision matrix。",
    tags: ["matrix", "2x2"],
    docHref: "/docs/cdl/presets/quadrant",
    diagram: presetQuadrant,
  },
  {
    id: "chartPie",
    slug: "chart-pie",
    eyebrow: "CHART / PIE",
    title: "chart (pie)",
    subtitle: "pie chart、 category 比率の可視化。",
    tags: ["chart", "pie"],
    docHref: "/docs/cdl/presets/chart",
    diagram: presetChartPie,
  },
  {
    id: "chartLine",
    slug: "chart-line",
    eyebrow: "CHART / LINE",
    title: "chart (line)",
    subtitle: "line chart、 時系列 metric の trend 可視化。",
    tags: ["chart", "line"],
    docHref: "/docs/cdl/presets/chart",
    diagram: presetChartLine,
  },
  {
    id: "gantt",
    slug: "gantt",
    eyebrow: "GANTT / TIMELINE",
    title: "gantt",
    subtitle: "Release timeline、 task 別 duration bar。",
    tags: ["timeline", "gantt"],
    docHref: "/docs/cdl/presets/gantt",
    diagram: presetGantt,
  },
  {
    id: "flowchart",
    slug: "flowchart",
    eyebrow: "FLOWCHART / DECISION",
    title: "flowchart",
    subtitle: "2 lane 承認フロー。 approval / rejection 分岐、 decision diamond。",
    tags: ["approval", "decision"],
    docHref: "/docs/cdl/presets/flowchart",
    diagram: presetFlowchart,
  },
  {
    id: "network",
    slug: "network",
    eyebrow: "NETWORK / TOPOLOGY",
    title: "network",
    subtitle: "Office NW topology、 firewall / switch / server segment。",
    tags: ["network", "nw"],
    docHref: "/docs/cdl/presets/network",
    diagram: presetNetwork,
  },
  {
    id: "stateMachine2",
    slug: "state-machine-2",
    eyebrow: "STATE / FSM 拡張",
    title: "stateMachine2",
    subtitle: "拡張 FSM (nested state + action + entry/exit)。",
    tags: ["fsm", "nested"],
    docHref: "/docs/cdl/presets/state-machine-2",
    diagram: presetStateMachine2,
  },
];
